### DISCUSSION TITLE
Minor doc improvement: example for extra_args

### DISCUSSION THREAD

**Discussion by akiross** [containers/ansible-podman-collections#399] [Ideas]
Hey,

I just started using ansible with podman and I hit a minor hiccup when using `extra_args`: I needed to use some `--build-arg`, but for some reason I did not realize `extra_args` was more general and I just assumed it was precisely expecting a list of variables for `--build-arg`. So, I tried to do the following:

```
- name: Build with an argument
  containers.podman.podman_image:
    ...
    build:
      extra_args: "FOO=bar"  # error!
```
and got a rather cryptic error: `Error: accepts at most 1 arg(s), received 2` (the error is clear, but what is causing that is not as clear).
In retrospect, `extra_args` was obviously meant to be used like:

```
- name: Build with an argument
  containers.podman.podman_image:
    ...
    build:
      extra_args: "--build-arg FOO=bar"
```

So, just to avoid someone does the same mistake, I'm proposing to add an example to the documentation showing how to use `extra_args`, for example by passing `--build-arg FOO=bar`.

That's it. Thank you for your great work with podman and ansible!
