### DISCUSSION TITLE
How to use this collection for a simple create and update container workflow

### DISCUSSION THREAD

**Discussion by CyberFox001** [containers/ansible-podman-collections#514] [General]
Hello,

I use this collection on a few playbooks and roles, but there is a simple workflow for which I still have doubts on how to do it.

## What I want to do

What I want to do is simple:
* Create a container the first time the playbook is run
* For each next run of the playbook, if the container image have an update, recreate the container with the new image but keep all its settings

An image is considered updated if the digest in the local storage is different than the one of the remote image.

## What I think to do

After reading the documentation of this collection, all I can think is something like that:
``` yaml
tasks:
  - name: Pull an image
    containers.podman.podman_image:
      name: docker.io/library/postgres
      tag: latest
      force: yes
    notify:
    - Recreate postgres
  
  - name: Run container
    containers.podman.podman_container:
      name: pgsql
      image: docker.io/library/postgres:latest
      state: started
      ports:
        - "5432:5432"
  
handlers:
  - name: Recreate postgres
     containers.podman.podman_container:
      name: pgsql
      recreate: yes
```

But I don't know if it will work when an update will be available. Maybe the recreation of the container make it lose all its settings. Maybe it will not work for another reason.

I can't found enough information in the doc to help me found a simple way to do my workflow.

## A better way ?

And, is it the best way ? For a simple workflow like this, should we have a simple setting in `podman_container` to do it with a single task ? 

Like a `image_update` setting that manage the recreation of the container when an update of the image is available ?

With this option, the previous workflow will be:
``` yaml
tasks:
  - name: Run container
    containers.podman.podman_container:
      name: pgsql
      image: docker.io/library/postgres:latest
      image_update: yes
      state: started
      ports:
        - "5432:5432"
```

**Comment by sshnaidm** [comment]
>  Create a container the first time the playbook is run
> For each next run of the playbook, if the container image have an update, recreate the container with the new image but keep all its settings

I think just running the same task should be fine. But use `image_strict: true` to detect changes in same image.
Like this for example:
```yaml
    - name: Run container
      containers.podman.podman_container:
        name: container1
        image: testimg
        state: started
        command: sleep 3h
        image_strict: true
        volumes:
          - /tmp/test:/test
        ports:
          - 10025:10025
      register: container1
```
Change `testimg`, run again and it will recreate the container.
