### DISCUSSION TITLE
http_proxy doesn't seem to work

### DISCUSSION THREAD

**Discussion by metasikander** [containers/ansible-podman-collections#519] [Q&A] [answered]
Does anyone know if env.vir. works with these modules?
I'm specifically trying to pull images through the http_proxy, but it doesn't work with the module.
It works when doing it manually on the same machine with the same user.

```yaml
- name: Pull images
  containers.podman.podman_image:
    name: "{{ item }}"
  loop:
    - docker.io/library/mariadb:{{ mariadb_version }}
    - docker.io/library/redis:{{ redis_version }}
    - docker.io/library/nextcloud:{{ nextcloud_version }}
    - docker.io/library/nextcloud:fpm-alpine
  environment: "{{ proxy_env }}"
```

**Comment by sshnaidm** [comment]
What do you have in  `"{{ proxy_env }}"` ?

**Reply by metasikander** [reply]
```yaml
vars:
  proxy_env:
    http_proxy: http://proxy.localproxy.com:8000
    https_proxy: http://proxy.localproxy.com:8000
```

**Reply by metasikander** [reply]
this is what i get with -vvvvv:
`EXEC /bin/sh -c 'http_proxy=http://proxy.localproxy.com:8000 https_proxy=http://proxy.localproxy.com:8000 /usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-1669122721.1867423-7772-258380084058210/AnsiballZ_podman_image.py && sleep 0'`

**Reply by metasikander** [reply]
it also works with shell, but i would prefer to use the module:

```yaml
- name: Pull Images
  ansible.builtin.shell: podman pull {{ item }} && sleep 0
  loop:
    - docker.io/library/mariadb:{{ mariadb_version }}
    - docker.io/library/redis:{{ redis_version }}
    - docker.io/library/nextcloud:{{ nextcloud_version }}
    - docker.io/library/nextcloud:fpm-alpine
  environment: "{{ proxy_env }}"
```

**Comment by sshnaidm** [comment, marked as answer]
Do you use `gather_facts: true`?
This worked for me:
```yaml
- hosts: localhost
  gather_facts: true
  vars:
    proxy_env:
      http_proxy: http://proxy.localproxy.com:8000
      https_proxy: http://proxy.localproxy.com:8000

  tasks:
    - name: pull
      containers.podman.podman_image:
        name: alpine:3.3
      environment: "{{ proxy_env }}"
```
