### DISCUSSION TITLE
ANSIBLE_PODMAN_EXTRA_ARGS and ANSIBLE_PODMAN_EXECUTABLE vars

### DISCUSSION THREAD

**Discussion by mahespth** [containers/ansible-podman-collections#665] [Ideas]
Hey,

I'm trying to work with a scenario with a remote podman instances and while I'm able to change the executable from podman to podman-remote for the modules it occurred to me that the connection/podman.py already has two options that if applied to all the modules would solve my problems and it would also (to me) make sense that these are applied throughout as would be suggested by the ANSIBLE_ vars.

Would there be any objection to adding the following to the modules ? Have I overlooked something ?

Thanks.

```yaml
      podman_extra_args:
        description:
          - Extra arguments to pass to the podman command line.
        default: ''
        ini:
          - section: defaults
            key: podman_extra_args
        vars:
          - name: ansible_podman_extra_args
        env:
          - name: ANSIBLE_PODMAN_EXTRA_ARGS
      podman_executable:
        description:
          - Executable for podman command.
        default: podman
        vars:
          - name: ansible_podman_executable
        env:
          - name: ANSIBLE_PODMAN_EXECUTABLE
```
