### DISCUSSION TITLE
Building an image with a new name

### DISCUSSION THREAD

**Discussion by lmilbaum** [containers/ansible-podman-collections#740] [Q&A] [answered]
The new image, lets call it: temp_image doesn't exist yet. 
The following code doesn't work because it tries to pull the image and throws the error:
```
fatal: [test_environment_host]: FAILED! => {"changed": false, "msg": "Failed to pull image temp_image:latest"}
```

```
  - name: Build Temp image
    containers.podman.podman_image:
      name: "temp_image"
      build:
        file: /tmp/Containerfile
      state: build
```

**Comment by sshnaidm** [comment, marked as answer]
Please provide `path` of build context directory, like you do for Podman: `podman build /path/to/dir -f Containerfile`.
```yaml
- name: Build Temp image
    containers.podman.podman_image:
      name: "temp_image"
      path: /tmp/
      build:
        file: /tmp/Containerfile
      state: build
```
You can see examples in the module docs: https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_image_module.html#examples
