### DISCUSSION TITLE
Quadlet "restart on change"-workflow

### DISCUSSION THREAD

**Discussion by wnhrt** [containers/ansible-podman-collections#883] [Q&A]
Is there a straight forward workflow to only restart updated quadlets?

I got a list of quadlets:
```yaml
podman_quadlet_base:
  state: quadlet
  quadlet_file_mode: '0640'

podman_quadlets:
  - name: NAME1
    image: IMAGE1
    ...
  - name: NAME2
    image: IMAGE2
    ...
```

generate them:
```yaml
- name: Build quadlets
  containers.podman.podman_container: "{{ item | ansible.builtin.combine(podman_quadlet_base) }}"
  loop: "{{ podman_quadlets }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Systemd daemon-reload
```

and start them:
```yaml
- name: Start container services
  systemd_service:
    name: "{{ item.name }}"
    state: started
    scope: "user"
    enabled: true
  loop: "{{ podman_quadlets }}"
  loop_control:
    label: "{{ item.name }}"
```

I could use the last block to restart them, but that would restart all containers, even if only one changes. Which is not good for containers with longer shutdown/boot time.
I thought about using `register: quadlets` and check which container was changed, but wasn't able to filter the data structure for the respective container.
