### ISSUE TITLE
Container restarts

### ISSUE THREAD

**Issue by amenzhinsky** [containers/ansible-podman-collections#161]
Hi there.

For now restarting containers with the collection is not very elegant opposed to docker_container:

```yaml
docker_container:
  name: postgres
  restart: yes
```

Whereas podman requires all container parameters but they can be pulled from `podman inspect`:

```yaml
podman_container:
  name: postgres
  restart: yes
  image: postgres:latest
  # volume, env, restart_policy, etc.
```

For now I'm sticking to this very simple workaround:

```yaml
command: podman restart postgres
```

**Comment by sshnaidm** [comment]
It can be an action which requires name of container only, fair enough.

**Comment by sshnaidm** [comment]
You can try:

```yaml
      containers.podman.podman_container:
        name: container
        restart: true
```
