### ISSUE TITLE
Root mount is not idemponent

### ISSUE THREAD

**Issue by amenzhinsky** [containers/ansible-podman-collections#162]
The following task always reports changed state:

```yaml
- name: Create node_exporter container
  containers.podman.podman_container:
    name: node_exporter
    image: docker.io/prom/node-exporter:v1.0.1
    volume:
      - /:/host:ro
```

```
TASK [Create node_exporter container] ************************************************************************************************************************
--- before
+++ after
@@ -1 +1 @@
-volume - ['/:/host']
+volume - [':/host']

TASK [Create node_exporter container] ************************************************************************************************************************
--- before
+++ after
@@ -1 +1 @@
-volume - ['/:/host']
+volume - [':/host']
```
It removes/adds root slash iteratively.

I'm using the latest tag version.
