### ISSUE TITLE
Examples of the ansible connection plugin for podman on remote hosts

### ISSUE THREAD

**Issue by sebastian-luna-valero** [containers/ansible-podman-collections#172]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I have been looking for examples on how to use the Ansible connection plugin for podman on remote hosts, without success.

All examples I have found so far just work with the Ansible connection plugin when both Ansible and podman containers are deployed on the same host. For example: https://blog.tomecek.net/post/ansible-and-podman-can-play-together-now/

I am probably missing something obvious but it would be great if a couple of examples were added to:

https://docs.ansible.com/ansible/2.10/collections/containers/podman/podman_connection.html

Would this be possible, please?

Many thanks,
Sebastian

**Comment by RobVerduijn** [comment]
I second this request,

Currently you have to be really persistent/desperate to even consider using the podman/buildah connection type.

Even after using ansible for some years now for all kinds ( vmware/network/fortios/cisco ) the only obvious thing I saw is that every last one of them has it's own interpretation on how to use a connection plugin and that each one of them (including yours) requires many hours of googling to get them to work due to poor documentation.

Good documentation with real working examples would make it a lot easier for people to start using this collection.

Rob

**Comment by FilBot3** [comment]
I imagine that the podman connection plugin operates like the docker one. It probably will require the socket to be enabled, and then Ansible can connect to it.

* https://stackoverflow.com/a/64218043

**Comment by m00nwtchr** [comment]
You can just do this:
```yaml
- name: Add container to inventory
  ansible.builtin.add_host:
    name: container_name
    ansible_connection: containers.podman.podman
    podman_extra_args: "--url ssh://{{ ansible_user }}@{{ ansible_host }}/run/podman/podman.sock"
```
But it would be nice if this was supported transparently, like with the docker connector.
