### ISSUE TITLE
Migrate podman modules from Ansible into collection

### ISSUE THREAD

**Issue by sshnaidm** [containers/ansible-podman-collections#2]
using current migration scenario:
```collection_migration/scenarios/containers/containers.yml```
```yaml
podman:
  connection:
    - buildah.py
    - podman.py
  modules:
    - cloud/podman/__init__.py
    - cloud/podman/podman_container_info.py
    - cloud/podman/podman_image_info.py
    - cloud/podman/podman_image.py
    - cloud/podman/podman_volume_info.py
  module_utils:
    - podman/common.py
    - podman/__init__.py
  integration:
    - connection_podman/*
    - podman_*/*
    - podman_*/*/*
    - setup_podman/*
    - setup_podman/*/*

```
