### ISSUE TITLE
plugins/modules/podman_container.py include output from is_different function in return values

### ISSUE THREAD

**Issue by dchats1** [containers/ansible-podman-collections#20]
Hi,

When testing the podman_container.py module, I noticed it kept recreating my containers somewhat unexpectedly. It turns out, for the container I was testing with (quay.io/prometheus/prometheus) I needed to set the `workdir` argument since the default in the module was different from what the container used. To find this I had to print out dff_func from the is_different function to see which argument I needed to add. I think it may be useful to include which arguments the module sees as different in the return values for easy debugging.

Thanks,
David

**Comment by sshnaidm** [comment]
@dchats1 can you please write playbooks that you run to test and how to reproduce the issue? You can run ansible-playbook --diff to see the difference in containers, no need to print from function. So `workdir` is not "/" by default for your case? Please submit output of "--diff" and inspect for container.
If I understand the issue correct, we'll need to remove `workdir` from defaults.

**Comment by dchats1** [comment]
@sshnaidm I wasn't aware of the --diff flag, that accomplishes exactly what I was looking for, thank you!

In the case of the quay.io/prometheus/prometheus container the `workdir` set by the container is /prometheus. Here is the task and the output from --diff:
```
- name: Run Prometheus Container
  containers.podman.podman_container:
    name: prometheus
    image: quay.io/prometheus/prometheus:v2.17.1
    network: host
    volume:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/prometheus/data:/prometheus
    state: started
```
```
--- before
+++ after
@@ -1 +1 @@
-workdir - /prometheus
+workdir - /
```

Adding `workdir: /prometheus` to the task fixes that.

I don't think the workdir needs to be removed from the defaults, but it might be helpful to have an extra flag that lets the module ignore params that aren't set by the user. Maybe something like this:
https://github.com/dchats1/ansible-podman-collections/commit/56922b71a519ee94ab910bea306a9ad8b9badf2c
