### ISSUE TITLE
Allow containers to stop gracefully when recreating

### ISSUE THREAD

**Issue by eliasnorrby** [containers/ansible-podman-collections#202]
/kind feature

**Description**

Consider the following use case: we want to continually deploy an application (`app`) using the `latest` tag. Thus, we have the following task in our playbook:

```yaml
- name: Start container
  podman_container:
    name: "app"
    image: "app-image:latest"
    recreate: true
```

With `recrate: true`, the following actions will be performed:

```bash
podman rm -f app
podman run --name app app-image:latest
```

**Request**

Instead of forcefully removing the container, allow it to stop gracefully by first running `podman stop`.
