### ISSUE TITLE
podman_pod stopped destroys containers in pod

### ISSUE THREAD

**Issue by PrymalInstynct** [containers/ansible-podman-collections#215]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**
### Role Tasks
```
---
- name: "Create Gitea Container Users"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
  with_items:
    - { name: 'gitea', comment: 'Gitea Server', uid: '5003' }

- name: "COPY | Setup .bashrc for Gitea Container Users"
  copy:
    src: '.bashrc'
    dest: "/home/{{ item }}"
  with_items:
    - gitea

- name: "Check if Lingering is enabled for Gitea User"
  stat:
    path: "/var/lib/systemd/linger/gitea"
  register: gitea_lingering
  changed_when: no

- name: "Enabled Lingering for Gitea User"
  command: loginctl enable-linger gitea
  when: not gitea_lingering.stat.exists

- name: "Pull Gitea Image"
  become: yes
  become_user: gitea
  podman_image:
    name: gitea/gitea
    tag: latest-rootless
    state: present

- name: "Pull PostgreSQL Image"
  become: yes
  become_user: gitea
  podman_image:
    name: postgres
    tag: '9.6'
    state: present

- name: "Add Firewalld Rule for Gitea Container"
  become: yes
  become_user: root
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 3000/tcp
    - 2222/tcp

- name: "Create Gitea Pod"
  become: yes
  become_user: gitea
  podman_pod:
    name: gitea
    state: started
    publish:
      - 3000:3000/tcp
      - 2222:2222/tcp

- name: "Create Gitea PostgreSQL Container"
  become: yes
  become_user: gitea
  podman_container:
    name: gitea-db
    pod: gitea
    image: postgres:9.6
    state: started
    env:
      POSTGRES_USER: 'gitea'
      POSTGRES_PASSWORD: 'gitea'
      POSTGRES_DB: 'gitea'
    volume:
      - gitea-db:/var/lib/postgresql/data

- name: "Create Gitea Container"
  become: yes
  become_user: gitea
  podman_container:
    name: gitea-app
    pod: gitea
    image: gitea/gitea:latest-rootless
    state: started
    env:
      DB_TYPE: 'postgres'
      DB_HOST: 'localhost:5432'
      DB_NAME: 'gitea'
      DB_USER: 'gitea'
      DB_PASSWD: 'gitea'
      ROOT_URL: 'http://10.10.1.20:3000'
      APP_NAME: 'HomeLab'
    volume:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/localtime:/etc/localtime:ro

- name: "Check for Gitea Service File"
  become: yes
  become_user: gitea
  stat:
    path: /home/gitea/.config/systemd/user/pod-gitea.service
  register: gitea_pod
  changed_when: no

- name: "Create systemd/user directory for Gitea"
  become: yes
  become_user: gitea
  file:
    path: /home/gitea/.config/systemd/user
    state: directory
  when: not gitea_pod.stat.exists | bool

- name: "Create Gitea Service"
  become: yes
  become_user: gitea
  shell: podman generate systemd --name gitea --files
  args:
    chdir: /home/gitea/.config/systemd/user/
  when: not gitea_pod.stat.exists | bool

- name: "Create Gitea Service"
  become: yes
  become_user: gitea
  shell: podman generate systemd --name gitea --files
  args:
    chdir: /home/gitea/.config/systemd/user/

- name: "Stop Gitea Container"
  become: yes
  become_user: gitea
  podman_container:
    name: gitea-app
    pod: gitea
    state: stopped

- name: "Stop Gitea Database Container"
  become: yes
  become_user: gitea
  podman_container:
    name: gitea-db
    pod: gitea
    state: stopped

- name: "Stop Gitea Pod"
  become: yes
  become_user: gitea
  podman_pod:
    name: gitea
    state: stopped

- name: "Enable Gitea Container Services"
  become: yes
  become_user: gitea
  environment:
    XDG_RUNTIME_DIR: "/run/user/5003"
  systemd:
    name: pod-gitea.service
    state: started
    enabled: yes
    daemon_reload: yes
    scope: user

```

**Describe the results you received:**
I get an error when the systemd service tries to start
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to start service pod-wekan.service: Job for pod-wekan.service failed because the control process exited with error code.\nSee \"systemctl --user status pod-wekan.service\" and \"journalctl --user -xe\" for details.\n"}
```

**Describe the results you expected:**
I expect the systemd service to start correctly

**Additional information you deem important (e.g. issue happens only occasionally):**
If I replace:
```
- name: "Stop Gitea Pod"
  become: yes
  become_user: gitea
  podman_pod:
    name: gitea
    state: stopped
```
with
```
- name: "Stop Gitea Pod"
  become: yes
  become_user: gitea
  command: podman pod stop gitea
```
I get the expected result

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman v1.4.3
```

**Output of `ansible --version`:**

```
ansible 2.9.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/zimmermanc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

**Output of `podman version`:**

```
podman version 2.2.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.22-3.module+el8.3.1+9857+68fb1526.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: a40e3092dbe499ea1d85ab339caea023b74829b9'
  cpus: 16
  distribution:
    distribution: '"rhel"'
    version: "8.3"
  eventLogger: file
  hostname: subzero.prymal.linux
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-240.10.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 1053212672
  memTotal: 75975507968
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module+el8.3.1+9857+68fb1526.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4225560576
  swapTotal: 8589930496
  uptime: 96h 12m 22.55s (Approximately 4.00 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 3
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: "2"
  Built: 1612819146
  BuiltTime: Mon Feb  8 14:19:06 2021
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-7.module+el8.3.1+9857+68fb1526.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
See Above
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

### truncated because its long and the rest of the role is fine
```
TASK [rhel-8-kvm-host : Stop Gitea Database Container] ****************************************************
task path: /home/zimmermanc/Projects/Homelab-Build/roles/rhel-8-kvm-host/tasks/gitea_container.yml:141
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: zimmermanc
<127.0.0.1> EXEC /bin/sh -c 'echo ~zimmermanc && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/tmp `"&& mkdir "` echo /var/tmp/ansible-tmp-1614602667.1594503-390972-68064028734823 `" && echo ansible-tmp-1614602667.1594503-390972-68064028734823="` echo /var/tmp/ansible-tmp-1614602667.1594503-390972-68064028734823 `" ) && sleep 0'
Using module file /usr/share/ansible/collections/ansible_collections/containers/podman/plugins/modules/podman_container.py
<127.0.0.1> PUT /home/zimmermanc/.ansible/tmp/ansible-local-389019hdgwt34w/tmphfcms6r1 TO /var/tmp/ansible-tmp-1614602667.1594503-390972-68064028734823/AnsiballZ_podman_container.py
<127.0.0.1> EXEC /bin/sh -c 'setfacl -m u:gitea:r-x /var/tmp/ansible-tmp-1614602667.1594503-390972-68064028734823/ /var/tmp/ansible-tmp-1614602667.1594503-390972-68064028734823/AnsiballZ_podman_container.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=znvebjfjvgfpwdhyzdzuelkkbbwlgkdd] password:" -u gitea /bin/sh -c '"'"'echo BECOME-SUCCESS-znvebjfjvgfpwdhyzdzuelkkbbwlgkdd ; /usr/libexec/platform-python /var/tmp/ansible-tmp-1614602667.1594503-390972-68064028734823/AnsiballZ_podman_container.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/tmp/ansible-tmp-1614602667.1594503-390972-68064028734823/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "actions": [
        "stopped gitea-db"
    ],
    "changed": true,
    "container": {
        "AppArmorProfile": "",
        "Args": [
            "postgres"
        ],
        "BoundingCaps": [
            "CAP_AUDIT_WRITE",
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FOWNER",
            "CAP_FSETID",
            "CAP_KILL",
            "CAP_MKNOD",
            "CAP_NET_BIND_SERVICE",
            "CAP_NET_RAW",
            "CAP_SETFCAP",
            "CAP_SETGID",
            "CAP_SETPCAP",
            "CAP_SETUID",
            "CAP_SYS_CHROOT"
        ],
        "Config": {
            "Annotations": {
                "io.container.manager": "libpod",
                "io.kubernetes.cri-o.ContainerType": "container",
                "io.kubernetes.cri-o.Created": "2021-03-01T05:44:17.73861788-07:00",
                "io.kubernetes.cri-o.SandboxID": "gitea",
                "io.kubernetes.cri-o.TTY": "false",
                "io.podman.annotations.autoremove": "FALSE",
                "io.podman.annotations.init": "FALSE",
                "io.podman.annotations.privileged": "FALSE",
                "io.podman.annotations.publish-all": "FALSE",
                "org.opencontainers.image.stopSignal": "2"
            },
            "AttachStderr": false,
            "AttachStdin": false,
            "AttachStdout": false,
            "Cmd": [
                "postgres"
            ],
            "CreateCommand": [
                "podman",
                "container",
                "run",
                "--name",
                "gitea-db",
                "--pod",
                "gitea",
                "--env",
                "POSTGRES_USER=gitea",
                "--env",
                "POSTGRES_PASSWORD=gitea",
                "--env",
                "POSTGRES_DB=gitea",
                "--volume",
                "gitea-db:/var/lib/postgresql/data",
                "--detach=True",
                "postgres:9.6"
            ],
            "Domainname": "",
            "Entrypoint": "docker-entrypoint.sh",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/9.6/bin",
                "TERM=xterm",
                "container=podman",
                "PG_VERSION=9.6.21-1.pgdg90+1",
                "PGDATA=/var/lib/postgresql/data",
                "POSTGRES_USER=gitea",
                "PG_MAJOR=9.6",
                "POSTGRES_PASSWORD=gitea",
                "POSTGRES_DB=gitea",
                "GOSU_VERSION=1.12",
                "LANG=en_US.utf8",
                "HOSTNAME=gitea",
                "HOME=/root"
            ],
            "Hostname": "gitea",
            "Image": "docker.io/library/postgres:9.6",
            "Labels": null,
            "OnBuild": null,
            "OpenStdin": false,
            "StdinOnce": false,
            "StopSignal": 2,
            "Tty": false,
            "Umask": "0022",
            "User": "",
            "Volumes": null,
            "WorkingDir": "/"
        },
        "ConmonPidFile": "/run/user/5003/containers/overlay-containers/10272f5e30b1d0dd69820f3b56c4bda2c4ea036626e1810acdeb156ef11a82c9/userdata/conmon.pid",
        "Created": "2021-03-01T05:44:17.73861788-07:00",
        "Dependencies": [
            "fc70905bb568cce342b2615c3cd21c04895b59f85dc23575b71875f5c5cd64a6"
        ],
        "Driver": "overlay",
        "EffectiveCaps": [
            "CAP_AUDIT_WRITE",
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FOWNER",
            "CAP_FSETID",
            "CAP_KILL",
            "CAP_MKNOD",
            "CAP_NET_BIND_SERVICE",
            "CAP_NET_RAW",
            "CAP_SETFCAP",
            "CAP_SETGID",
            "CAP_SETPCAP",
            "CAP_SETUID",
            "CAP_SYS_CHROOT"
        ],
        "ExecIDs": [],
        "ExitCommand": [
            "/usr/bin/podman",
            "--root",
            "/home/gitea/.local/share/containers/storage",
            "--runroot",
            "/run/user/5003/containers",
            "--log-level",
            "error",
            "--cgroup-manager",
            "cgroupfs",
            "--tmpdir",
            "/run/user/5003/libpod/tmp",
            "--runtime",
            "runc",
            "--storage-driver",
            "overlay",
            "--storage-opt",
            "overlay.mount_program=/bin/fuse-overlayfs",
            "--events-backend",
            "file",
            "container",
            "cleanup",
            "10272f5e30b1d0dd69820f3b56c4bda2c4ea036626e1810acdeb156ef11a82c9"
        ],
        "GraphDriver": {
            "Data": {
                "LowerDir": "/home/gitea/.local/share/containers/storage/overlay/bb7a8c0114ae4718598ffe2ed70507f32d977cac3b57de31d3fc7aa180228717/diff:/home/gitea/.local/share/containers/storage/overlay/b82dcf8f863fad9c79790e49d7a5e8acaa6cb2da411c198186c4ff7c6a9ed16c/diff:/home/gitea/.local/share/containers/storage/overlay/32d6a39436592992b8e412cf4794a2c0b4f4be604a6f75d1bad67c665f3003c8/diff:/home/gitea/.local/share/containers/storage/overlay/9d3a83fe8aa8d1e5a2fe6f77cbdaa6db47b076d0e6ccf6e671655784850e94a8/diff:/home/gitea/.local/share/containers/storage/overlay/2bba3e197f8ad5251fcdd37d7ca91e9aa84629bfc02cf589d132d2c8f6a8576b/diff:/home/gitea/.local/share/containers/storage/overlay/aaeca0bd77299371eaeac69fd0ceb40941d79ad0e2f1191dde303c33717eb6e4/diff:/home/gitea/.local/share/containers/storage/overlay/50be361de69285caf5aa5d9a14f7e22da0b4a6e2ed3051a330bdff3d226d2aff/diff:/home/gitea/.local/share/containers/storage/overlay/ec3854503165cc9f82a9a09ccef41ecd5c56ecbc121ca856e53a71f490b20b97/diff:/home/gitea/.local/share/containers/storage/overlay/4afcb6ffd6c08f8d32ebf5fb2a9a0c8fe8ff2ed85bfc37d520471db3964094c5/diff:/home/gitea/.local/share/containers/storage/overlay/22d9a72198a0a75f28982dec45391ec0fd4ed6d9c3d827986bb66779066d0d23/diff:/home/gitea/.local/share/containers/storage/overlay/4754b5a530f08ce896f76b860e221f0550cdc5ff0c108f855841cff9cba0e24d/diff:/home/gitea/.local/share/containers/storage/overlay/285c424c1d4d2c19fbbe60a8322a083547ce3fe811a78fc4ec77480b6181b0e9/diff:/home/gitea/.local/share/containers/storage/overlay/08a2d60a90a8a2d0208e54ed381d798fb2406ef29920683fdb18bc55d9888712/diff:/home/gitea/.local/share/containers/storage/overlay/55d13762c439e07035670ec521fe3d72d3c9650d767190c93b8d051185a64d98/diff",
                "UpperDir": "/home/gitea/.local/share/containers/storage/overlay/a6a0879f268077772f88bd690f13267495db2ddb4045e54af46431cadf32688b/diff",
                "WorkDir": "/home/gitea/.local/share/containers/storage/overlay/a6a0879f268077772f88bd690f13267495db2ddb4045e54af46431cadf32688b/work"
            },
            "Name": "overlay"
        },
        "HostConfig": {
            "AutoRemove": false,
            "Binds": [
                "gitea-db:/var/lib/postgresql/data:rw,rprivate,nosuid,nodev,rbind"
            ],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceWriteIOps": null,
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "CapAdd": [],
            "CapDrop": [],
            "Cgroup": "",
            "CgroupConf": null,
            "CgroupManager": "cgroupfs",
            "CgroupMode": "host",
            "CgroupParent": "/libpod_parent/9a9b9df3416f90094a28228bf713a2f73f680f0289e5e7598b24b7a1a6e58d7a",
            "Cgroups": "default",
            "ConsoleSize": [
                0,
                0
            ],
            "ContainerIDFile": "",
            "CpuCount": 0,
            "CpuPercent": 0,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpuShares": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": [],
            "IOMaximumBandwidth": 0,
            "IOMaximumIOps": 0,
            "IpcMode": "container:fc70905bb568cce342b2615c3cd21c04895b59f85dc23575b71875f5c5cd64a6",
            "Isolation": "",
            "KernelMemory": 0,
            "Links": null,
            "LogConfig": {
                "Config": null,
                "Type": "k8s-file"
            },
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": 0,
            "NanoCpus": 0,
            "NetworkMode": "container:fc70905bb568cce342b2615c3cd21c04895b59f85dc23575b71875f5c5cd64a6",
            "OomKillDisable": false,
            "OomScoreAdj": 0,
            "PidMode": "private",
            "PidsLimit": 0,
            "PortBindings": {},
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "RestartPolicy": {
                "MaximumRetryCount": 0,
                "Name": ""
            },
            "Runtime": "oci",
            "SecurityOpt": [],
            "ShmSize": 65536000,
            "Tmpfs": {},
            "UTSMode": "container:fc70905bb568cce342b2615c3cd21c04895b59f85dc23575b71875f5c5cd64a6",
            "Ulimits": [],
            "UsernsMode": "",
            "VolumeDriver": "",
            "VolumesFrom": null
        },
        "HostnamePath": "/run/user/5003/containers/overlay-containers/10272f5e30b1d0dd69820f3b56c4bda2c4ea036626e1810acdeb156ef11a82c9/userdata/hostname",
        "HostsPath": "/run/user/5003/containers/overlay-containers/fc70905bb568cce342b2615c3cd21c04895b59f85dc23575b71875f5c5cd64a6/userdata/hosts",
        "Id": "10272f5e30b1d0dd69820f3b56c4bda2c4ea036626e1810acdeb156ef11a82c9",
        "Image": "a8d8c70f674729ec462176873fb0c5c2103a85bb4e0f9ad2c0c6fcbc2c3bf340",
        "ImageName": "docker.io/library/postgres:9.6",
        "IsInfra": false,
        "LogPath": "/home/gitea/.local/share/containers/storage/overlay-containers/10272f5e30b1d0dd69820f3b56c4bda2c4ea036626e1810acdeb156ef11a82c9/userdata/ctr.log",
        "LogTag": "",
        "MountLabel": "system_u:object_r:container_file_t:s0:c451,c901",
        "Mounts": [
            {
                "Destination": "/var/lib/postgresql/data",
                "Driver": "local",
                "Mode": "",
                "Name": "gitea-db",
                "Options": [
                    "nosuid",
                    "nodev",
                    "rbind"
                ],
                "Propagation": "rprivate",
                "RW": true,
                "Source": "/home/gitea/.local/share/containers/storage/volumes/gitea-db/_data",
                "Type": "volume"
            }
        ],
        "Name": "gitea-db",
        "Namespace": "",
        "NetworkSettings": {
            "Bridge": "",
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "HairpinMode": false,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "MacAddress": "",
            "Ports": {
                "2222/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "2222"
                    }
                ],
                "3000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3000"
                    }
                ]
            },
            "SandboxID": "",
            "SandboxKey": "/run/user/5003/netns/cni-69baf8bc-3c08-b533-d9e5-f5e13cac9169"
        },
        "OCIConfigPath": "/home/gitea/.local/share/containers/storage/overlay-containers/10272f5e30b1d0dd69820f3b56c4bda2c4ea036626e1810acdeb156ef11a82c9/userdata/config.json",
        "OCIRuntime": "runc",
        "Path": "docker-entrypoint.sh",
        "Pod": "9a9b9df3416f90094a28228bf713a2f73f680f0289e5e7598b24b7a1a6e58d7a",
        "ProcessLabel": "system_u:system_r:container_t:s0:c451,c901",
        "ResolvConfPath": "/run/user/5003/containers/overlay-containers/fc70905bb568cce342b2615c3cd21c04895b59f85dc23575b71875f5c5cd64a6/userdata/resolv.conf",
        "RestartCount": 0,
        "Rootfs": "",
        "State": {
            "Dead": false,
            "Error": "",
            "ExitCode": 0,
            "FinishedAt": "2021-03-01T05:44:28.250889835-07:00",
            "Healthcheck": {
                "FailingStreak": 0,
                "Log": null,
                "Status": ""
            },
            "OOMKilled": false,
            "OciVersion": "1.0.2-dev",
            "Paused": false,
            "Pid": 0,
            "Restarting": false,
            "Running": false,
            "StartedAt": "2021-03-01T05:44:18.783751475-07:00",
            "Status": "exited"
        },
        "StaticDir": "/home/gitea/.local/share/containers/storage/overlay-containers/10272f5e30b1d0dd69820f3b56c4bda2c4ea036626e1810acdeb156ef11a82c9/userdata"
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "authfile": null,
            "blkio_weight": null,
            "blkio_weight_device": null,
            "cap_add": null,
            "cap_drop": null,
            "cgroup_parent": null,
            "cgroupns": null,
            "cgroups": null,
            "cidfile": null,
            "cmd_args": null,
            "command": null,
            "conmon_pidfile": null,
            "cpu_period": null,
            "cpu_rt_period": null,
            "cpu_rt_runtime": null,
            "cpu_shares": null,
            "cpus": null,
            "cpuset_cpus": null,
            "cpuset_mems": null,
            "debug": false,
            "detach": true,
            "detach_keys": null,
            "device": null,
            "device_read_bps": null,
            "device_read_iops": null,
            "device_write_bps": null,
            "device_write_iops": null,
            "dns": null,
            "dns_option": null,
            "dns_search": null,
            "entrypoint": null,
            "env": null,
            "env_file": null,
            "env_host": null,
            "etc_hosts": null,
            "executable": "podman",
            "expose": null,
            "force_restart": false,
            "gidmap": null,
            "group_add": null,
            "healthcheck": null,
            "healthcheck_interval": null,
            "healthcheck_retries": null,
            "healthcheck_start_period": null,
            "healthcheck_timeout": null,
            "hostname": null,
            "http_proxy": null,
            "image": null,
            "image_strict": false,
            "image_volume": null,
            "init": null,
            "init_path": null,
            "interactive": null,
            "ip": null,
            "ipc": null,
            "kernel_memory": null,
            "label": null,
            "label_file": null,
            "log_driver": null,
            "log_level": null,
            "log_opt": null,
            "mac_address": null,
            "memory": null,
            "memory_reservation": null,
            "memory_swap": null,
            "memory_swappiness": null,
            "mount": null,
            "name": "gitea-db",
            "network": null,
            "no_hosts": null,
            "oom_kill_disable": null,
            "oom_score_adj": null,
            "pid": null,
            "pids_limit": null,
            "pod": "gitea",
            "privileged": null,
            "publish": null,
            "publish_all": null,
            "read_only": null,
            "read_only_tmpfs": null,
            "recreate": false,
            "restart_policy": null,
            "rm": null,
            "rootfs": null,
            "security_opt": null,
            "shm_size": null,
            "sig_proxy": null,
            "state": "stopped",
            "stop_signal": null,
            "stop_timeout": null,
            "subgidname": null,
            "subuidname": null,
            "sysctl": null,
            "systemd": null,
            "tmpfs": null,
            "tty": null,
            "uidmap": null,
            "ulimit": null,
            "user": null,
            "userns": null,
            "uts": null,
            "volume": null,
            "volumes_from": null,
            "workdir": null
        }
    },
    "podman_actions": [
        "podman stop gitea-db"
    ],
    "stderr": "",
    "stderr_lines": [],
    "stdout": "10272f5e30b1d0dd69820f3b56c4bda2c4ea036626e1810acdeb156ef11a82c9\n",
    "stdout_lines": [
        "10272f5e30b1d0dd69820f3b56c4bda2c4ea036626e1810acdeb156ef11a82c9"
    ]
}

TASK [rhel-8-kvm-host : Stop Gitea Pod] *******************************************************************
task path: /home/zimmermanc/Projects/Homelab-Build/roles/rhel-8-kvm-host/tasks/gitea_container.yml:149
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: zimmermanc
<127.0.0.1> EXEC /bin/sh -c 'echo ~zimmermanc && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/tmp `"&& mkdir "` echo /var/tmp/ansible-tmp-1614602668.9099503-391204-97191331406165 `" && echo ansible-tmp-1614602668.9099503-391204-97191331406165="` echo /var/tmp/ansible-tmp-1614602668.9099503-391204-97191331406165 `" ) && sleep 0'
Using module file /usr/share/ansible/collections/ansible_collections/containers/podman/plugins/modules/podman_pod.py
<127.0.0.1> PUT /home/zimmermanc/.ansible/tmp/ansible-local-389019hdgwt34w/tmpqzaofac3 TO /var/tmp/ansible-tmp-1614602668.9099503-391204-97191331406165/AnsiballZ_podman_pod.py
<127.0.0.1> EXEC /bin/sh -c 'setfacl -m u:gitea:r-x /var/tmp/ansible-tmp-1614602668.9099503-391204-97191331406165/ /var/tmp/ansible-tmp-1614602668.9099503-391204-97191331406165/AnsiballZ_podman_pod.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=inqsqhmmefxaprfoxfibotvtolrxygmb] password:" -u gitea /bin/sh -c '"'"'echo BECOME-SUCCESS-inqsqhmmefxaprfoxfibotvtolrxygmb ; /usr/libexec/platform-python /var/tmp/ansible-tmp-1614602668.9099503-391204-97191331406165/AnsiballZ_podman_pod.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/tmp/ansible-tmp-1614602668.9099503-391204-97191331406165/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "actions": [
        "recreated gitea"
    ],
    "changed": true,
    "invocation": {
        "module_args": {
            "add_host": null,
            "cgroup_parent": null,
            "debug": false,
            "dns": null,
            "dns_opt": null,
            "dns_search": null,
            "executable": "podman",
            "hostname": null,
            "infra": null,
            "infra_command": null,
            "infra_conmon_pidfile": null,
            "infra_image": null,
            "ip": null,
            "label": null,
            "label_file": null,
            "mac_address": null,
            "name": "gitea",
            "network": null,
            "no_hosts": null,
            "pod_id_file": null,
            "publish": null,
            "recreate": false,
            "share": null,
            "state": "stopped"
        }
    },
    "pod": {
        "CgroupParent": "/libpod_parent",
        "CgroupPath": "/libpod_parent/a9064e0ee6744a60f28b82a47bedcf6d78d03848f1e815eb858b5cbbf933f8c4",
        "Containers": [
            {
                "Id": "5c7bc4d90a038e2549490d2db28dd535816301c489085c7dbafbe742e8d6d3e7",
                "Name": "a9064e0ee674-infra",
                "State": "configured"
            }
        ],
        "CreateCgroup": true,
        "CreateCommand": [
            "podman",
            "pod",
            "create",
            "--name",
            "gitea"
        ],
        "CreateInfra": true,
        "Created": "2021-03-01T05:44:30.850229167-07:00",
        "Hostname": "gitea",
        "Id": "a9064e0ee6744a60f28b82a47bedcf6d78d03848f1e815eb858b5cbbf933f8c4",
        "InfraConfig": {
            "DNSOption": null,
            "DNSSearch": null,
            "DNSServer": null,
            "HostAdd": null,
            "HostNetwork": false,
            "NetworkOptions": null,
            "Networks": null,
            "NoManageHosts": false,
            "NoManageResolvConf": false,
            "PortBindings": {},
            "StaticIP": "",
            "StaticMAC": ""
        },
        "InfraContainerID": "5c7bc4d90a038e2549490d2db28dd535816301c489085c7dbafbe742e8d6d3e7",
        "Name": "gitea",
        "NumContainers": 1,
        "SharedNamespaces": [
            "uts",
            "ipc",
            "net"
        ],
        "State": "Created"
    },
    "podman_actions": [
        "podman pod rm -f gitea",
        "podman pod create --name gitea"
    ],
    "stderr": "",
    "stderr_lines": [],
    "stdout": "a9064e0ee6744a60f28b82a47bedcf6d78d03848f1e815eb858b5cbbf933f8c4\n",
    "stdout_lines": [
        "a9064e0ee6744a60f28b82a47bedcf6d78d03848f1e815eb858b5cbbf933f8c4"
    ]
}

TASK [rhel-8-kvm-host : Enable Gitea Container Services] **************************************************
task path: /home/zimmermanc/Projects/Homelab-Build/roles/rhel-8-kvm-host/tasks/gitea_container.yml:156
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: zimmermanc
<127.0.0.1> EXEC /bin/sh -c 'echo ~zimmermanc && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/tmp `"&& mkdir "` echo /var/tmp/ansible-tmp-1614602671.300597-391525-124751739158569 `" && echo ansible-tmp-1614602671.300597-391525-124751739158569="` echo /var/tmp/ansible-tmp-1614602671.300597-391525-124751739158569 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/system/systemd.py
<127.0.0.1> PUT /home/zimmermanc/.ansible/tmp/ansible-local-389019hdgwt34w/tmpjwxg1dsc TO /var/tmp/ansible-tmp-1614602671.300597-391525-124751739158569/AnsiballZ_systemd.py
<127.0.0.1> EXEC /bin/sh -c 'setfacl -m u:gitea:r-x /var/tmp/ansible-tmp-1614602671.300597-391525-124751739158569/ /var/tmp/ansible-tmp-1614602671.300597-391525-124751739158569/AnsiballZ_systemd.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=ppooywdfgdlvnstndiexbvvjdxtbjvip] password:" -u gitea /bin/sh -c '"'"'echo BECOME-SUCCESS-ppooywdfgdlvnstndiexbvvjdxtbjvip ; XDG_RUNTIME_DIR=/run/user/5003 /usr/libexec/platform-python /var/tmp/ansible-tmp-1614602671.300597-391525-124751739158569/AnsiballZ_systemd.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/tmp/ansible-tmp-1614602671.300597-391525-124751739158569/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reexec": false,
            "daemon_reload": true,
            "enabled": true,
            "force": null,
            "masked": null,
            "name": "pod-gitea.service",
            "no_block": false,
            "scope": "user",
            "state": "started",
            "user": null
        }
    },
    "msg": "Unable to start service pod-gitea.service: Job for pod-gitea.service failed because the control process exited with error code.\nSee \"systemctl --user status pod-gitea.service\" and \"journalctl --user -xe\" for details.\n"
}
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
