### ISSUE TITLE
Why podman_image ignore "registries.insecure"

### ISSUE THREAD

**Issue by atomlab** [containers/ansible-podman-collections#23]
I have an error

```
- name: Pull an cardano image
  containers.podman.podman_image:
       name: "hub:9080/cardano"
       tag: 3.2.0-13
       auth_file: /root/.podman-auth.json
       state: present
```

>TASK [currency/cardano-podman : Pull an cardano image] *************************************************
fatal: [ada-03]: FAILED! => {"changed": false, "msg": "Failed to pull image hub:9080/cardano:3.2.0-13. Error: Error: error pulling image \"hub:9080/cardano:3.2.0-13\": unable to pull hub:9080/cardano:3.2.0-13: unable to pull image: Error initializing source docker://hub:9080/cardano:3.2.0-13: error pinging docker registry hub:9080: Get https://hub:9080/v2/: http: server gave HTTP response to HTTPS client\n"}

But if I run `podman pull` manually it works fine. 
```
root@ada-03:~# podman pull -q hub:9080/cardano:3.2.0-13
151ea90a6aa201aa601e29d19807ccd3726156808a6473fce5209f6d73b24e5e
root@ada-03:~#
```

Does `podman_image` ignore `/etc/containers/registries.conf` file?

```
# cat /etc/containers/registries.conf
[registries.search]
registries = ['docker.io', 'quay.io']

[registries.insecure]
registries = ['hub:9080', 'hub:9090']
```
