### ISSUE TITLE
podman_container: State 'started' required image to be configured!

### ISSUE THREAD

**Issue by carbolymer** [containers/ansible-podman-collections#247]
Use the following task definition

```
  - "containers.podman.podman_container":
      "name": "database-backup"
      "state": "started"
    "name": "Changing state of container \"database-backup\" to started"
```

**Actual Result:**
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "State 'started' required image to be configured!"}`

**Expected result:**
The task should not require image parameter - if the container with the provided name exists, it should be started.

**Comment by sshnaidm** [comment]
I think it's better to leave it as is. Otherwise there is no way to separate create&start container and "just started one that was already created". You can use `state: restarted` in order to start created container. Tell me please if it works for you.

**Comment by carbolymer** [comment]
There's no `restarted` state: https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html#parameter-state

**Comment by sshnaidm** [comment]
You can run like this:
```yaml
    - name: test cont
      containers.podman.podman_container:
        name: mycont
        state: absent

    - name: test cont
      containers.podman.podman_container:
        name: mycont
        state: created
        image: alpine
        command: sleep 1h
        interactive: true
        labels:
          zuzu: lalal

    - name: start cont
      containers.podman.podman_container:
        name: mycont
        restart: true
```

Probably I can add alias `start` to `restart` if it will be helpful.

> That's simple, if the container exists, just start it, otherwise build one. If image is not provided, ansible would fail in the latter case. 

It can be a case when changing the containers, for example:

```yaml
- name: test cont
      containers.podman.podman_container:
        name: mycont
        state: created
        image: alpine
        command: sleep 1h
        interactive: true
        labels:
          zuzu: lalal

- name: test cont2
      containers.podman.podman_container:
        name: mycont
        state: started
        image: alpine
        command: sleep 2h

```
Need to take it into consideration as well.
