### ISSUE TITLE
Do not strip image name+tag from push destination when transport=dir

### ISSUE THREAD

**Issue by lowne** [containers/ansible-podman-collections#264]
/kind bug

**Description**

[This](https://github.com/containers/ansible-podman-collections/blob/ba763e2988c4d3f94940695a5699f26fb94ed31f/plugins/modules/podman_image.py#L651) isn't true when `transport`=`dir`, which results in all the images ending up into one giant broken pile if the the naked (i.e. unmangled) tag is used as part of the destination path (who's afraid of colons in filenames? :shark: )

**Steps to reproduce the issue:**

```
- containers.podman.podman_image:
    state: build
    path: "{{ build_dir }}"
    build:
      format: docker
      rm: no
    name: "{{ image_tag }}"
    push: yes
    push_args:
      transport: dir
      dest: "{{ some_dir }}/{{ image_tag }}"
```

**Describe the results you received:**
`[WARNING]: Image name and tag are automatically added to push_args['dest']. Destination changed to {{some_dir}}` + 
a giant mess

**Describe the results you expected:**
A neat directory structure
