### ISSUE TITLE
Ansible not stopping when error occurs in container

### ISSUE THREAD

**Issue by c-goes** [containers/ansible-podman-collections#277]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When the command in the container errors Ansible continues the play. 

**Steps to reproduce the issue:**

```
- name: Failing task
  podman_container:
    name: testctr
    rm: yes
    image: docker.io/alpine
    state: present
    command: "false"

- name: Failing task 2
  command: "false"

```

**Describe the results you received:**

First task succeeds, second fails

```
TASK [Failing task] ***********************************************************************
changed: [host1]

TASK [Failing task 2] *********************************************************************
fatal: [host1]: FAILED! => {"changed": true, "cmd": ["false"], "delta": "0:00:00.013890", "end": "2021-08-01 15:20:38.962060", "msg": "non-zero return code", "rc": 1, "start": "2021-08-01 15:20:38.948170", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
``` 

**Describe the results you expected:**

Both tasks fail

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman             1.6.1  
containers.podman 1.6.1 
```

**Output of `ansible --version`:**

```
ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/home/r/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/r/envs/ansible/lib/python3.8/site-packages/ansible
  ansible collection location = /home/r/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/r/envs/ansible/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.11.2
  libyaml = False
```

**Output of `podman version`:**

```
Version:      3.0.0
API Version:  3.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/arm
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
(paste your output here)
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by sshnaidm** [comment]
When you run it with podman in CLI it's the same:
```
$ podman run --name testctr --rm --detach=True docker.io/alpine false
bc3a26b4fe794ffee4bfb5724dbf88ce2acf800ee5d19c00a65e16a295523e98
$ echo $?
0
```
If you want it to fail, run without `--detach`:
```
$ podman run --name testctr --rm docker.io/alpine false
$ echo $?
1
```
and same with ansible:
```
- name: Failing task
      containers.podman.podman_container:
        name: testctr
        rm: yes
        detach: false
        image: docker.io/alpine
        state: present
        command: "false"
```
About `detach` I think better to ask in podman project.
