### ISSUE TITLE
Podman image push only, seems to not do so

### ISSUE THREAD

**Issue by sean-m-sullivan** [containers/ansible-podman-collections#285]
/kind bug

**Description**
Using Podman images to push an built ansible ee image, and it tries to pull image an image, even though that is set to false. 

**Steps to reproduce the issue:**

1.
```
  containers.podman.podman_image:
    auth_file:
    build:
      annotation:
      cache: true
      extra_args:
      force_rm: false
      format: oci
      rm: true
      volume:
    ca_cert_dir:
    executable: podman
    force: false
    name: ee_tools
    password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
    path:
    pull: false
    push: true
    push_args:
      compress:
      dest: quay.io/ssulliva/ee_tools
      format:
      remove_signatures:
      sign_by:
      transport:
    state: present
    tag: latest
    username: ssulliva
    validate_certs:
 ``
I get the message
msg: Failed to pull image ee_tools:latest

The local podman images
```
podman images
REPOSITORY                            TAG      IMAGE ID      CREATED         SIZE
quay.io/ssulliva/ee_tools             latest   1a1e85769616  4 hours ago     737 MB
localhost/ee_tools                    latest   1a1e85769616  4 hours ago     737 MB
```
**Describe the results you expected:**
Expect it to be pushed, but definitely do not expect to get an error about pulling when trying to push a prebuilt image.


**Version of the `containers.podman` collection:**
```
containers.podman          1.6.2
```

**Output of `ansible --version`:**

```
ansible [core 2.11.2]
```

**Output of `podman version`:**

```
(paste your output here)
```
podman version 3.0.1
```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
(paste your output here)
```

**Comment by sshnaidm** [comment]
@sean-m-sullivan please provide exact playbook/task you are running for reproducing, thanks.

**Comment by sean-m-sullivan** [comment]
This is the playbook
```
---
- name: Playbook to configure ansible controller organizations
  hosts: localhost
  gather_facts: false
  collections:
    - sean_m_sullivan.tower_utilities
    - containers.podman
  vars:
    builder_dir: /tmp
    ee_registry_dest: quay.io/ssulliva/ee_tools
    ee_name: ee_tools 
    ee_continaer_runtime: docker
    ee_python:
      - podman
      - ansible-lint
      - ansible-builder
    ee_collections:
      - name: awx.awx
      - name: redhat_cop.tower_utilities
      - name: containers.podman

  tasks:

    - name: Build EE
      include_role:
        name: ee_builder
``` 
and the role task file it calls
```

- name: "Run the Ansible Builder Program"
  become: true
  command: "ansible-builder create -f {{ builder_dir }}/execution_environment.yml -t {{ ee_name }} --container-runtime={{ ee_container_runtime }}"
  args:
    chdir: "{{ builder_dir }}/"
  changed_when: true   # these will always run and will always report “changed” otherwise

- name: push image to registry
  community.docker.docker_image:
    name: "{{ ee_name }}"
    push: yes
    pull: false
    source: local
    repository: "{{ ee_registry_dest }}"
    ca_cert: "{{ ee_ca_cert | default(omit) }}"
    validate_certs: "{{ ee_validate_certs | default(omit) }}"
```
