### ISSUE TITLE
command blocks have problems with spaces

### ISSUE THREAD

**Issue by spyderz42** [containers/ansible-podman-collections#304]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When using podman_containers to set up a gitlab runner ran into a problem when trying to use spaces in the command block. There appears to be no way to escape the spaces as the python code splits on spaces without checking if they are in quotes.

**Steps to reproduce the issue:**

1. create a task to register a gitlab-runner. Add a cli of `--description "This is a test"` and the created pod will error out

**Describe the results you received:**

Usually got an error: `PANIC: The registration-token needs to be entered ` as the token was after the description line

**Describe the results you expected:**

I expected that the gitlab-runner would be registered with the gitlab instance

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman             1.6.2  
```

**Output of `ansible --version`:**

```
ansible [core 2.11.4] 
  config file = None
...
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True
```

**Output of `podman version`:**

```
podman version 3.3.1

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by sshnaidm** [comment]
Please provide a full task that reproduces the problem, it's unclear what is going on. Do not ignore the issue template, it asks for an essential information, try to fill it up. Not everyone is familiar with gitlab runner.

**Comment by spyderz42** [comment]
```yaml
    - name: Register runners
      containers.podman.podman_container:
        command: >
          register
            --non-interactive
            --url {{ gitlab_url }}
            --description "{{ item.group }} - {{ gitlab_runner_description }}""
            --docker-dns {{ dns_server }}
            --docker-image docker:latest
            --docker-privileged=true
            --docker-volumes /var/run/podman/podman.sock:/var/run/podman/podman.sock
            --executor docker
            --registration-token {{ item.token }}
            --tls-ca-file=/etc/gitlab-runner/certs/ca.crt
        env:
          DOCKER_HOST: /var/run/podman/podman.sock
        image: gitlab/gitlab-runner:latest
        name: gitlab-runner-register
        privileged: true
        volumes:
          - "{{ gitlab_conf_dir }}:/etc/gitlab-runner/"
          - "/var/run/podman/podman.sock:/var/run/podman/podman.sock"
      loop: "{{ gitlab_registration_tokens }}"
```
