### ISSUE TITLE
Generate systemd does not append `.service` to unit files

### ISSUE THREAD

**Issue by anthr76** [containers/ansible-podman-collections#309]
Use something like

```
    - name: run minio
      containers.podman.podman_container:
        name: minio
        image: "quay.io/minio/minio:RELEASE.2021-09-18T18-09-59Z"
        state: started
        generate_systemd:
          path: "{{ ansible_user_dir }}/.config/systemd/user/foo.service"
          restart_policy: always
        command:
          - "server"
          - "/data"
          - "--console-address"
          - ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        env:
          MINIO_UPDATE: "off"
          MINIO_PROMETHEUS_AUTH_TYPE: "public"
        volume:
          - "/tank/minio:/data:z"
      become: false
  ```

Observe that the generated systemd script will go to `/home/1000/.config/system/user/foo.service/container-minio` Where it should really be `/home/1000/.config/system/user/foo.service`
