### ISSUE TITLE
Allow empty string for container_prefix, pod_prefix and separator in generate_systemd

### ISSUE THREAD

**Issue by zephyros-dev** [containers/ansible-podman-collections#319]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The podman generate systemd command allow using empty string in its parameter. I haven't found the same way to do it in the generate_systemd options

**Steps to reproduce the issue:**

1. Run some playbook like this:
```
- name: HTTP Echo Container
  containers.podman.podman_container:
    name: "echo-test"
    image: "mendhak/http-https-echo"
    ports:
      - "18080:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro,z"
    restart_policy: on-failure
    generate_systemd:
      container_prefix: ""
      pod_prefix: ""
      separator: ""
      path: "/home/user/.config/systemd/user/"
    state: "started"
```

**Describe the results you received:**

The service file is created, but with default parameter name. For example, the above will create **container-echo-test.service**

**Describe the results you expected:**

The example above, with the podman generate systemd command and empty string

```
podman generate systemd --new --name --files --container-prefix "" --pod-prefix "" --separator "" echo-test
```
The generated file will be named **echo-test.service**
