### ISSUE TITLE
podman_secret adds \n to secret

### ISSUE THREAD

**Issue by wabuMike** [containers/ansible-podman-collections#330]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The plugin containers.podman.podman_secret adds a newline (\n) to secrets provided with the parameter `data`.

**Steps to reproduce the issue:**

1. Add a task creating a secret with `podman secret`:

```yml
- name: Create secret with shell
  shell: "printf test123 | podman secret create TEST_1 -"
```

2. Add another task creating a secret with `containers.podman.podman_secret`:

```yml
- name: Create secret with podman_secret
  containers.podman.podman_secret:
    state: present
    name: TEST_2
    data: test123
```

3. Run a container with the secrets:

`podman run --rm -it --name alpine-test --secret TEST_1 --secret TEST_2 alpine`

4. Print  secrets:

```sh
/ # cat -e /run/secrets/TEST_1
test123/ # 
```

```sh
/ # cat -e /run/secrets/TEST_2
test123$
/ # 
```

**Describe the results you expected:**

When creating a secret with containers.podman.podman_secret, I expect the secret to have the exact same characters as I define with the parameter 'data'. In the example above, I would expect `cat -e /run/secrets/TEST_2` to print `test123/ #` as it does for `cat -e /run/secrets/TEST_1`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:** 1.8.1
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
git show --summary
commit a0377fbd240f39d35c8b833b1f961c61b445fc1b (HEAD -> master, origin/master, origin/HEAD)
Author: Oliver Walsh <owalsh@redhat.com>
Date:   Tue Oct 19 15:18:22 2021 +0100
```

**Output of `ansible --version`:**

```
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/michael/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/michael/.local/lib/python3.8/site-packages/ansible
  executable location = /home/michael/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 100:3.3.1-1 amd64 [installed]
podman/unknown 100:3.3.1-1 arm64
podman/unknown 100:3.3.1-1 armhf
podman/unknown 100:3.3.1-1 s390x
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
---
- name: Test podman_secret
  hosts: all
  tasks:
    - name: Create secret with shell
      shell: "printf test123 | podman secret create TEST_1 -"

    - name: Create secret with podman_secret
      containers.podman.podman_secret:
        state: present
        name: TEST_2
        data: test123
```
