### ISSUE TITLE
`generate_systemd` doesn't generates container's services without pod restarting

### ISSUE THREAD

**Issue by 50U10FCA7** [containers/ansible-podman-collections#441]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`containers.podman.podman_pod.generate_systemd` doesn't generates container unit files without restarting the pod.

**Steps to reproduce the issue:**

1. Create a pod with container.
```yml
- name: Apply manifest
  become_method: sudo
  become: yes
  containers.podman.podman_play:
    state: created
    kube_file: "manifest.yaml"
```

2.  Generate the unit files.
```yml
- name: Create Unit files
  become_method: sudo
  become: yes
  containers.podman.podman_pod:
    name: "my_pod"
    generate_systemd:
      path: /etc/systemd/system
```

3. Check the directory where unit files are generated.

**Describe the results you received:**

`pod-my_pod.service` file in `/etc/systemd/system`

**Describe the results you expected:**

`pod-my_pod.service` and `container-my_pod-my_container.service` files in `/etc/systemd/system`

**Additional information you deem important (e.g. issue happens only occasionally):**

If replace 2 reproduce step with the following:
```yml
- name: Create Unit files
  become_method: sudo
  become: yes
  containers.podman.podman_pod:
    name: "my_pod"
    state: restarted # Without this container files won't be generated.
    generate_systemd:
      path: /etc/systemd/system
```

everything work fine.

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman      1.9.1  
containers.podman      1.9.3  
```

**Output of `ansible --version`:**

```
ansible [core 2.12.5]
  config file = /project/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.13 (main, May 24 2022, 21:13:51) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.1
  libyaml = True
```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18
Built:        Fri May  6 16:15:54 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

``` yaml
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 99.76
    systemPercent: 0.11
    userPercent: 0.13
  cpus: 20
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: target_machine_hostname
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.17.9-300.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 66210648064
  memTotal: 67421003776
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.4-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 38m 57.06s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 158902235136
  graphRootUsed: 10022039552
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.0
  Built: 1651853754
  BuiltTime: Fri May  6 16:15:54 2022
  GitCommit: ""
  GoVersion: go1.18
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.0-1.fc36.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
---
- hosts: target_machine_hostname
  connection: ssh
  tasks:
    - name: Copy manifest file
      become_method: sudo
      become: yes
      copy: src="~/projects/admin/test_manifest.yaml"
            dest="/etc/test_manifest.yaml"
            owner=root
            mode=0600

    - name: Apply manifest of app
      become_method: sudo
      become: yes
      containers.podman.podman_play:
        state: created
        kube_file: "/etc/test_manifest.yaml"

    - name: Create Unit files of app
      become_method: sudo
      become: yes
      containers.podman.podman_pod:
        name: "test_pod"
        generate_systemd:
          path: /etc/systemd/system
```

test_manifest.yml
```yml
---

kind: Pod
apiVersion: v1
metadata:
  name: test_pod
  labels:
    app: test_pod
spec:
  containers:
    - name: test_container
      image: docker.io/nginx:latest
      ports:
        - name: http
          containerPort: 80
          hostPort: 80
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```
ansible-playbook [core 2.12.5]
  config file = /project/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible-playbook
  python version = 3.9.13 (main, May 24 2022, 21:13:51) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.1
  libyaml = True
Using /project/ansible.cfg as config file
Vault password: 
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test.yml *************************************************************************************************************************************************************************************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [target_machine_hostname] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /project/test.yml:2
ok: [target_machine_hostname]
META: ran handlers

TASK [Copy manifest file] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /project/test.yml:4
ok: [target_machine_hostname] => {"changed": false, "checksum": "fe58d537a47c2e8aa6c187491589ff1d0de669f0", "dest": "/etc/test_manifest.yaml", "gid": 0, "group": "root", "mode": "0600", "owner": "root", "path": "/etc/test_manifest.yaml", "size": 253, "state": "file", "uid": 0}

TASK [Apply manifest of app] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /project/test.yml:12
ok: [target_machine_hostname] => {"actions": ["/usr/bin/podman play kube --start=false /etc/test_manifest.yaml"], "changed": false, "stderr": [], "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [Create Unit files of app] ************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /project/test.yml:19
ok: [target_machine_hostname] => {"actions": [], "changed": false, "pod": {"CgroupParent": "machine.slice", "CgroupPath": "machine.slice/machine-libpod_pod_1e06d6bd8349be4cda61382174c36038381252f61e66e5f7a9a62bc5a15b697e.slice", "Containers": [{"Id": "67d898abfd1d5cca7d1ced4a6a6004a60d29aabb583486386256df7d5a1308aa", "Name": "1e06d6bd8349-infra", "State": "created"}], "CreateCgroup": true, "CreateCommand": ["podman", "pod", "create", "--name", "test_pod"], "CreateInfra": true, "Created": "2022-06-23T03:37:01.210208122Z", "Hostname": "", "Id": "1e06d6bd8349be4cda61382174c36038381252f61e66e5f7a9a62bc5a15b697e", "InfraConfig": {"DNSOption": null, "DNSSearch": null, "DNSServer": null, "HostAdd": null, "HostNetwork": false, "NetworkOptions": null, "Networks": ["podman"], "NoManageHosts": false, "NoManageResolvConf": false, "PortBindings": {}, "StaticIP": "", "StaticMAC": "", "pid_ns": "private", "userns": "host"}, "InfraContainerID": "67d898abfd1d5cca7d1ced4a6a6004a60d29aabb583486386256df7d5a1308aa", "Name": "test_pod", "NumContainers": 1, "SharedNamespaces": ["net", "uts", "ipc"], "State": "Created"}, "podman_actions": [], "podman_systemd": {"pod-test_pod": "# pod-test_pod.service\n# autogenerated by Podman 4.1.0\n# Thu Jun 23 03:38:57 UTC 2022\n\n[Unit]\nDescription=Podman pod-test_pod.service\nDocumentation=man:podman-generate-systemd(1)\nWants=network-online.target\nAfter=network-online.target\nRequiresMountsFor=\nRequires=\nBefore=\n\n[Service]\nEnvironment=PODMAN_SYSTEMD_UNIT=%n\nRestart=on-failure\nTimeoutStopSec=70\nExecStart=/usr/bin/podman start 1e06d6bd8349-infra\nExecStop=/usr/bin/podman stop -t 10 1e06d6bd8349-infra\nExecStopPost=/usr/bin/podman stop -t 10 1e06d6bd8349-infra\nPIDFile=/run/containers/storage/overlay-containers/67d898abfd1d5cca7d1ced4a6a6004a60d29aabb583486386256df7d5a1308aa/userdata/conmon.pid\nType=forking\n\n[Install]\nWantedBy=default.target\n"}, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************
target_machine_hostname  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical
