### ISSUE TITLE
command parameter appears to not handle quotation marks properly

### ISSUE THREAD

**Issue by andrewbedia** [containers/ansible-podman-collections#449]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
command parameter appears to not handle quotation marks properly (or I'm ignorant and new to ansible)

**Steps to reproduce the issue:**

1. Pass a command parameter that involves quotes
e.g. command: renew --deploy-hook "echo 1 > /var/lib/letsencrypt/complete"

**Describe the results you received:**
command gets passed to podman incorrectly

```
    "msg": "Can't run container certbot",
    "stderr": "usage: \n  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...\n\nCertbot can obtain and install HTTPS/TLS/SSL certificates.  By default,\nit will attempt to use a webserver both for obtaining and installing the\ncertificate. \ncertbot: error: unrecognized arguments: 1 > /var/lib/letsencrypt/complete\"\n",
    "stderr_lines": [
        "usage: ",
        "  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...",
        "",
        "Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,",
        "it will attempt to use a webserver both for obtaining and installing the",
        "certificate. ",
        "certbot: error: unrecognized arguments: 1 > /var/lib/letsencrypt/complete\""
    ],
    "stdout": "",
    "stdout_lines": []

````

**Describe the results you expected:**
I expect it to work like podman normally does in this situation. For example, the following run from the shell works perfectly:
```
podman run --rm --name certbot -it --pod webserver\
  -v /containers/certbot/cloudflare:/opt/certbot/cloudflare\
  -v /containers/certbot/etc/letsencrypt:/etc/letsencrypt\
  -v /containers/certbot/var/lib/letsencrypt:/var/lib/letsencrypt\
  -v /containers/webserver_nginx/var/www:/var/www\
  docker.io/certbot/dns-cloudflare:latest\
  renew --deploy-hook  "echo 1 > /var/lib/letsencrypt/complete"
```

**Additional information you deem important (e.g. issue happens only occasionally):**
My task looks like this
```
      - name: "run the certbot container"
        containers.podman.podman_container:
          image: docker.io/certbot/dns-cloudflare:latest
          state: started
          rm: yes
          volume:
            - /containers/certbot/cloudflare:/opt/certbot/cloudflare
            - /containers/certbot/etc/letsencrypt:/etc/letsencrypt
            - /containers/certbot/var/lib/letsencrypt:/var/lib/letsencrypt
            - /containers/webserver_nginx/var/www:/var/www
          pod: webserver
          detach: false
          command: renew --deploy-hook "echo 1 > /var/lib/letsencrypt/complete"
          name: certbot

```

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
# ansible-galaxy collection list | grep containers.podman
containers.podman 1.9.4
containers.podman             1.9.1

```

**Output of `ansible --version`:**

```
# ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

```

**Output of `podman version`:**

```
# podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7
```

**Output of `podman info --debug`:**

```
# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 87b7a9037cbd1d81288bdf2d6705dfda889f7cf9'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: <redacted>
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-372.9.1.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 262561792
  memTotal: 5992919040
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-2.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.8-2.module+el8.6.0+14877+f643d2d6.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 485h 45m 53.45s (Approximately 20.21 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 9
    paused: 0
    running: 9
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 11
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1650363392
  BuiltTime: Tue Apr 19 06:16:32 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
---
  - name: "renew certs"
    hosts: localhost

    tasks:

      - name: "prep env"
        ansible.builtin.file:
          path: /containers/certbot/var/lib/letsencrypt/complete
          state: absent

      - name: "run the certbot container"
        containers.podman.podman_container:
          image: docker.io/certbot/dns-cloudflare:latest
          state: started
          rm: yes
          volume:
            - /containers/certbot/cloudflare:/opt/certbot/cloudflare
            - /containers/certbot/etc/letsencrypt:/etc/letsencrypt
            - /containers/certbot/var/lib/letsencrypt:/var/lib/letsencrypt
            - /containers/webserver_nginx/var/www:/var/www
          pod: webserver
          detach: false
          command: renew --deploy-hook "echo 1 > /var/lib/letsencrypt/complete"
          name: certbot

```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```
# ansible-playbook renew-certs.yml -vv
ansible-playbook [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible-playbook
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: renew-certs.yml *******************************************************************************************************************************************************************************************************************
1 plays in renew-certs.yml

PLAY [renew certs] **************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
task path: /root/renew-certs.yml:2
ok: [localhost]
META: ran handlers

TASK [prep env] *****************************************************************************************************************************************************************************************************************************
task path: /root/renew-certs.yml:7
ok: [localhost] => {"changed": false, "path": "/containers/certbot/var/lib/letsencrypt/complete", "state": "absent"}

TASK [run the certbot container] ************************************************************************************************************************************************************************************************************
task path: /root/renew-certs.yml:12
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Can't run container certbot", "stderr": "usage: \n  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...\n\nCertbot can obtain and install HTTPS/TLS/SSL certificates.  By default,\nit will attempt to use a webserver both for obtaining and installing the\ncertificate. \ncertbot: error: unrecognized arguments: 1 > /var/lib/letsencrypt/complete\"\n", "stderr_lines": ["usage: ", "  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...", "", "Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,", "it will attempt to use a webserver both for obtaining and installing the", "certificate. ", "certbot: error: unrecognized arguments: 1 > /var/lib/letsencrypt/complete\""], "stdout": "", "stdout_lines": []}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
