### ISSUE TITLE
[DISCUSSION] How to replace easily Docker by Podman for Ansible Docker users?

### ISSUE THREAD

**Issue by sshnaidm** [containers/ansible-podman-collections#45]
**Issue**:
Right now a lot of Ansible users deploy Docker containers using `docker_*` modules of Ansible. Because Docker is not supported on RHEL-8/CnetOS-8 officially and user might want still to use their playbooks and roles, instead of rewriting them. Podman is supposed to replace Docker in RH-8 distros. Current there are a few `podman_*` modules.
How can we make migration of `docker_*` users as easy and transparent as possible?
For example task:
```yaml
- name: Run some docker container
  docker_container:
    name: grafana
    image: grafana
    detach: true
    ports:
      - 3000:3000
    env:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
```
What is the best solution (considering collections) that can allow user to continue using this task in Podman only host?
The ideal situation is:
```yaml
- hosts: all
  collections:
    - containers.whatever
  tasks:
... all tasks of users as is ....
```

Currently options on the table are (additional are welcome!):

1. To create action modules in `containers.whatever` collection. It will pick up podman and docker collections and each action module will trigger either docker or podman module, depending on what is on the host. Kind of `package` module model.
2. To make current Ansible Podman module similar to Docker one in options (they're almost are) and hack command line "docker" instead of "podman". Rename it to 'generic' or even to 'containers.docker'. Most of usual things would work. Some, like pods and other specific, will be available for Podman only.
3. To write a new `generic` container module basing on podman API v2, which should be a copy of Docker-Py. Write it from scratch with support of both Docker and Podman as underlying engines.
4. If podman API v2 will be similar to Docker-Py, then hack current Ansible Docker module for additional required things to support Podman. May require some sort of environment variables support, new/old options, and god knows what else.
Also there is an opened question what to do with specific Podman features like pods, play-kube and others. And what to do with Ansible Docker Compose feature.

/poll "Action modules to hide actual containers engine" "Replace by docker in command line" "Write a new generic module using future APIv2" "Hack current Docker module for using future APIv2"

**Comment by sshnaidm** [comment]
Amazingly, option 2 works as is:
```yaml
- name: Run docker hidden in podman
  containers.podman.podman_container:
    name: test-container
    image: alpine
    state: present
    executable: docker
    env:
      MYSQL_ROOT_PASSWORD: "2211"
```
```
"podman_actions": [
        "docker run --name test-container --env MYSQL_ROOT_PASSWORD=2211 --detach=True alpine"
    ]
```
```
$ docker ps -a
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS                      PORTS                    NAMES
13a5bc49ead3        alpine                 "/bin/sh"           21 minutes ago      Exited (0) 21 minutes ago                            test-container
```
So a little action plugin which will replace `executable` and maybe some options is very doable.
