### ISSUE TITLE
podman_container does not handle multiple networks with options.

### ISSUE THREAD

**Issue by kristvanbesien** [containers/ansible-podman-collections#467]
/kind bug

**Description**

When adding multiple networks to a container this fails when there are options added. 

**Steps to reproduce the issue:**

1.
Create a container with two networks, with options added to one. For example with this playbook snippet:

```
- name: Create an mdns reflector between iot and podnet
    containers.podman.podman_container:
      name: mdns-reflector
      image: flungo/avahi:multiarch
      env:
        REFLECTOR_ENABLE_REFLECTOR: yes
      network:
        - podnet
        - iot:ip=192.168.12.11
```
2.

Run.

**Describe the results you received:**

Got the following error:

`fatal: [kermit.wl.kri.st]: FAILED! => {"changed": false, "msg": "Can't run container mdns-reflector", "stderr": "Error: unable to find network with name or ID podnet,iot: network not found\n", "stderr_lines": ["Error: unable to find network with name or ID podnet,iot: network not found"], "stdout": "", "stdout_lines": []}`

**Describe the results you expected:**

Expected a container to be created, connected to networks "podnet" and "iot", with the IP address set on the iot network.

**Additional information you deem important**

The problem is, as far as I can see, due to the way that the network parameter is handled.
This is a list of strings, and the code does just concatenate the strings together, with a "," in between.

This breaks the podman invocation.

So what the module does is:

```
podman run -d --name=mdns-reflector \
--network podnet,iot:ip=192.168.12.11 \
-e REFLECTOR_ENABLE_REFLECTOR=yes \ 
flungo/avahi:multiarch
```

But what it should do is: 

```
podman run -d --name=mdns-reflector \
--network podnet  \
--network iot:ip=192.168.12.11 \
-e REFLECTOR_ENABLE_REFLECTOR=yes \ 
flungo/avahi:multiarch
```

**Version of the `containers.podman` collection:**

```
1.9.4
```
