### ISSUE TITLE
Publish ports breaks idempotency

### ISSUE THREAD

**Issue by rerime** [containers/ansible-podman-collections#485]
**BUG REPORT**

/kind bug

**Description**

**Steps to reproduce the issue:**

```
- name: Re-create minio container with systemd service.
  containers.podman.podman_container:
    name: minio
    image: '{{minio_image}}'
    command: 'server {{minio_servers}}'
    memory_reservation: 12884901888
    memory_swappiness: 0
    state: started
    recreate: no
    network: host
    publish:
        - '9000:9000'
        - '{{minio_console_port}}:{{minio_console_port}}' # console
    env:
      MINIO_ROOT_USER: '{{minio_root_user}}'
      MINIO_ROOT_PASSWORD: '{{minio_root_password}}'
      MINIO_ACCESS_KEY: '{{minio_root_user}}'
      MINIO_SECRET_KEY: '{{minio_root_password}}'
      MINIO_CONSOLE_ADDRESS: ':{{minio_console_port}}'
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_BROWSER_REDIRECT_URL: "{{ minio_browser_redirect_url | default() }}"
    volume:
      - /data/minio/data1:/data1
      - /data/minio/data2:/data2
    generate_systemd:
      path: /etc/systemd/system/
  become: yes
```

ansible-playbook --diff

```
TASK [minio : Re-create minio container with systemd service.] ***************************************************************************************************
--- before
+++ after
@@ -1 +1 @@
-publish - []
+publish - ['9000:9000', '9001:9001']
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman             1.9.4
```

**Output of `ansible --version`:**

```
ansible --version
ansible [core 2.13.1]

```

**Output of `podman version`:**

```
podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.7
Built:        Mon Jul 11 17:56:53 2022
OS/Arch:      linux/amd64
```
