### ISSUE TITLE
Does not delete generated systemd files on `state: absent`

### ISSUE THREAD

**Issue by nogweii** [containers/ansible-podman-collections#489]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Create a podman container that generates a systemd unit:

```yaml
- name: Create a redis container
  containers.podman.podman_container:
    name: redis
    image: docker.io/bitnami/redis:7.0
    state: present
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      time: 120
      new: true
    env_file: /etc/default/container-redis
    secrets:
      - redis-password
    volume:
      - /srv/containers/redis:/bitnami/redis/data
  notify:
    - Restart redis container
```

2. See that the service file was generated successfully:

```cli
$ ls -l /etc/systemd/system/container-redis.service
-rw-r--r-- 1 root root 944 Sep 29 19:16 /etc/systemd/system/container-redis.service
```

3. Run the same task again, but with `state: absent`

4. The file still exists

**Describe the results you expected:**

The generated service file is deleted.

**Version of the `containers.podman` collection:** git, bf67c7e0788758be4cac090c02be2eec01de3afe

**Output of `ansible --version`:**

```
ansible [core 2.13.4]
  config file = /home/nog/code/ansible-aethernet/ansible.cfg
  configured module search path = ['/home/nog/code/ansible-aethernet/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/nog/code/ansible-aethernet/.collections
  executable location = /usr/bin/ansible
  python version = 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True

```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.19
Git Commit:   62b324ddf718411b1d4d0ba8117c632f7f984a38-dirty
Built:        Thu Sep  8 06:52:54 2022
OS/Arch:      linux/amd64
```

Both the ansible controller (my laptop) and podman (on my VPS) are running Arch Linux.
