### ISSUE TITLE
Older Podman versions do not have running state in 'inspect' output, breaking idempotence

### ISSUE THREAD

**Issue by antonc42** [containers/ansible-podman-collections#499]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On older Podman versions, such as v1.6.4 in CentOS 7, the status of a pod is not included in the 'podman pod inspect <pod-name>' output. Instead, the 'podman pod ps --format json --filter name=<pod-name>' command contains the status. Since the running status cannot be found, the module assumes it is not started and attempts to start it every time. This breaks idempotence.

**Steps to reproduce the issue:**

1. Install `podman` from the package manager on CentOS 7.

2. Run task to start a new pod.  Status is changed as expected.
```
ansible centos7-host -m containers.podman.podman_pod -a 'name=test-pod state=started
```

4. Run the task again. Status is still changed, but should be okay. The task starts the pod again.
```
ansible centos7-host -m containers.podman.podman_pod -a 'name=test-pod state=started
```

**Describe the results you received:**
The task is changed and starts the pod again even though it is running.
```
tmp | CHANGED => {
    "actions": [
        "started test-pod"
    ],
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": true,
    "pod": {
        "Config": {
            "cgroupParent": "machine.slice",
            "created": "2022-10-27T14:20:56.73315778Z",
            "hostname": "test-pod",
            "id": "7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f",
            "infraConfig": {
                "infraPortBindings": null,
                "makeInfraContainer": true
            },
            "labels": {},
            "lockID": 0,
            "name": "test-pod",
            "sharesCgroup": true,
            "sharesIpc": true,
            "sharesNet": true,
            "sharesUts": true
        },
        "Containers": [
            {
                "id": "bcf26bafedeb6f725d724da170ec56f308b57dd5baccf95065998d613ec963a3",
                "state": "running"
            }
        ],
        "State": {
            "cgroupPath": "machine.slice/machine-libpod_pod_7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f.slice",
            "infraContainerID": "bcf26bafedeb6f725d724da170ec56f308b57dd5baccf95065998d613ec963a3"
        }
    },
    "podman_actions": [
        "podman pod start test-pod"
    ],
    "podman_systemd": {},
    "stderr": "",
    "stderr_lines": [],
    "stdout": "7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f\n",
    "stdout_lines": [
        "7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f"
    ]
}
```

**Describe the results you expected:**
The task is okay and the pod is not started again.
```
tmp | SUCCESS => {
    "actions": [],
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "pod": {
        "Config": {
            "cgroupParent": "machine.slice",
            "created": "2022-10-27T14:20:56.73315778Z",
            "hostname": "test-pod",
            "id": "7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f",
            "infraConfig": {
                "infraPortBindings": null,
                "makeInfraContainer": true
            },
            "labels": {},
            "lockID": 0,
            "name": "test-pod",
            "sharesCgroup": true,
            "sharesIpc": true,
            "sharesNet": true,
            "sharesUts": true
        },
        "Containers": [
            {
                "id": "bcf26bafedeb6f725d724da170ec56f308b57dd5baccf95065998d613ec963a3",
                "state": "running"
            }
        ],
        "State": {
            "cgroupPath": "machine.slice/machine-libpod_pod_7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f.slice",
            "infraContainerID": "bcf26bafedeb6f725d724da170ec56f308b57dd5baccf95065998d613ec963a3"
        }
    },
    "podman_actions": [],
    "podman_systemd": {},
    "stderr": "",
    "stderr_lines": [],
    "stdout": "",
    "stdout_lines": []
}
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman  1.9.4
```

**Output of `ansible --version`:**

```
ansible [core 2.13.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansible-collection-dev/.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/ansible-collection-dev/.venv/bin/ansible
  python version = 3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = False

```

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

``` yaml
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.11.7
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.8-1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.8, commit: f85c8b1ce77b73bcd48b2d802396321217008762'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 32904990720
  MemTotal: 33045471232
  OCIRuntime:
    name: runc
    package: runc-1.0.0-69.rc10.el7_9.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 524283904
  SwapTotal: 524283904
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: tmp
  kernel: 5.14.0-1054-oem
  os: linux
  rootless: false
  uptime: 14m 14.84s
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-6.el7_8.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: zfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-36.el7_9.x86_64
```

**Playbook you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
N/A, see steps to reproduce for ad-hoc command
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible --diff -vv centos7-host -m containers.podman.podman_pod -a 'name=test-pod state=started`

```
ansible [core 2.13.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansible-collection-dev/.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/ansible-collection-dev/.venv/bin/ansible
  python version = 3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = False
Using /etc/ansible/ansible.cfg as config file
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
META: ran handlers
redirecting (type: connection) ansible.builtin.lxd to community.general.lxd
tmp | CHANGED => {
    "actions": [
        "started test-pod"
    ],
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": true,
    "pod": {
        "Config": {
            "cgroupParent": "machine.slice",
            "created": "2022-10-27T14:20:56.73315778Z",
            "hostname": "test-pod",
            "id": "7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f",
            "infraConfig": {
                "infraPortBindings": null,
                "makeInfraContainer": true
            },
            "labels": {},
            "lockID": 0,
            "name": "test-pod",
            "sharesCgroup": true,
            "sharesIpc": true,
            "sharesNet": true,
            "sharesUts": true
        },
        "Containers": [
            {
                "id": "bcf26bafedeb6f725d724da170ec56f308b57dd5baccf95065998d613ec963a3",
                "state": "running"
            }
        ],
        "State": {
            "cgroupPath": "machine.slice/machine-libpod_pod_7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f.slice",
            "infraContainerID": "bcf26bafedeb6f725d724da170ec56f308b57dd5baccf95065998d613ec963a3"
        }
    },
    "podman_actions": [
        "podman pod start test-pod"
    ],
    "podman_systemd": {},
    "stderr": "",
    "stderr_lines": [],
    "stdout": "7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f\n",
    "stdout_lines": [
        "7c80d8f8eaac9b08dd121039b74908eed854e5eac111e203596a7b633a4d275f"
    ]
}
META: ran handlers
META: ran handlers

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
