### ISSUE TITLE
containers.podman.podman_network: Macvlan missing parent option

### ISSUE THREAD

**Issue by djarbz** [containers/ansible-podman-collections#534]
/kind feature

**Description**

I am attempting to create a MACVLAN on a specific interface and the 'parent' option is not available.

```yaml
- name: Create host bridge
  containers.podman.podman_network:
    name: "mv0"
    driver: macvlan
    opt:
      parent: "mv0"
    ip_range: "192.168.0.0/24"
    subnet: "192.168.0.0/24"
    gateway: "192.168.0.1"
    ipv6: false
  become: true
```

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman     1.10.1
```
