### ISSUE TITLE
Support podman image scp

### ISSUE THREAD

**Issue by hammerandtongs** [containers/ansible-podman-collections#536]
/kind feature

**Description**

Being able to use a direct transfer via image scp (without registry) would be very useful

https://docs.podman.io/en/latest/markdown/podman-image-scp.1.html

**Comment by sshnaidm** [comment]
@Noghpu this is a community project, you can submit a patch to add this feature or sponsor it.

**Comment by hammerandtongs** [comment]
So a very important issue is that podman scp copies regardless of whether the image is there or not already so I use a wrapped check of the image id to make sure its a necessary copy.

Without this check, I wouldn't recommend a straight wrapping of podman scp as it wouldn't be useful.

podmanimages.yaml

```
---
- hosts: workstations
  become: false  # We're running rootless, so no need for sudo
  vars:
    image_list:
      - "localhost/myimage:latest"
  tasks:
    - name: Process container images
      include_tasks: process_image.yml
      loop: "{{ image_list }}"
      loop_control:
        loop_var: item

```
process_image.yml

```
---
- name: Get local image ID
  command: podman images --format "{% raw %}{{.ID}}{% endraw %}" {{ item }}
  register: local_image
  changed_when: false
  delegate_to: localhost

- name: Get remote image ID
  command: podman images --format "{% raw %}{{.ID}}{% endraw %}" {{ item }}
  register: remote_image
  changed_when: false
  ignore_errors: yes

- name: Sync image if missing or different
  command: podman --ssh native image scp {{ item }} {{ inventory_hostname }}'::'
  when: local_image.stdout is defined and remote_image.stdout is defined and local_image.stdout != remote_image.stdout
  delegate_to: localhost

- name: Get remote image ID after sync
  command: podman images --format "{% raw %}{{.ID}}{% endraw %}" {{ item }}
  register: remote_image_after_sync
  changed_when: false

- name: Verify ID match after sync
  fail:
    msg: "ID mismatch after sync for {{ item }}. Local: {{ local_image.stdout }}, Remote: {{ remote_image_after_sync.stdout }}"
  when: local_image.stdout != remote_image_after_sync.stdout

- name: Verify synced image
  command: podman images --format "{% raw %}{{.Repository}}:{{.Tag}}{% endraw %}" {{ item }}
  register: final_image

- name: Display final image
  debug:
    var: final_image.stdout_lines
```
