### ISSUE TITLE
Support runlabels in containers.podman

### ISSUE THREAD

**Issue by pdostal** [containers/ansible-podman-collections#620]
Hello,

It would be nice to have [podman container runlabel](https://docs.podman.io/en/latest/markdown/podman-container-runlabel.1.html) module in `containers.podman`.

/kind feature

**Description**

Nowadays, we have the following:
```yaml
- name: Install all required parts for the container
  ansible.builtin.command: >-
    podman container runlabel install {{ container.image }}
  register: runlabel_install
  changed_when:
    - ('already exist' not in runlabel_install.stdout)
```

But that's not very pretty. I would appreciate something like:
```yaml
- name: Install all required parts for the container
  containers.podman.container_runlabel: install
```

With best regards
Pavel Dostál
