### ISSUE TITLE
absent + stop_timeout is not behaving as expected

### ISSUE THREAD

**Issue by KayARS** [containers/ansible-podman-collections#629]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The combination of state: absent and stop_timeout: 180
is not behaving as the same command from podman when using stop -t 180
**Steps to reproduce the issue:**

1. Spin up a container with a long running task that blocks the SIGTERM for infinite time
(e.g. a bash script:
 ```
#!/bin/bash 
# no-sigterm.sh
trap "" SIGTERM 
exec "$@"
```
-----
run with:
`no-sigterm.sh sleep 60000`
)

2. Create a task similar to this: 
- name: "Drop: {{container_name}}"
  containers.podman.podman_container:
    name: "{{container_name}}"
    state: absent
    stop_timeout: 180
  

**Describe the results you received:**

The ansible module will not wait for 180 seconds until it kills the process.

**Describe the results you expected:**

This shell command would wait for 180 seconds module.

- name: "Drop: {{container_name}}"
  shell: "podman stop -t 1800  {{container_name}} ; podman rm -f {{container_name}}"
  ignore_errors: true

Maybe there is also a misunderstanding in the documentation, if so it would be nice if you could tell me how to use it correctly to achieve the same outcome.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman             1.10.3
containers.podman             1.10.2
```

**Output of `ansible --version`:**

```
ansible [core 2.15.1]
```

**Output of `podman version`:**

```
╰─$ podman version
Client:       Podman Engine
Version:      4.4.4
API Version:  4.4.4
Go Version:   go1.19
Git Commit:   c8223435f49a860c8ac4281a85db39232745a7cb
Built:        Tue Mar 28 01:49:14 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.6.0
API Version:  4.6.0
Go Version:   go1.20.6
Built:        Fri Jul 21 14:22:41 2023
OS/Arch:      linux/arm64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
- name: Get timestamp from the system
  shell: "date +%Y-%m-%d%H-%M-%S"
  register: tstamp
  tags:
    - always
- name: Set variables
  set_fact:
    cur_date: "{{ tstamp.stdout[0:10]}}"
    cur_time: "{{ tstamp.stdout[10:]}}"
  tags:
    - always

- name: System timestamp - time
  debug:
    msg:  "Current date: {{ cur_time }}"
  tags:
    - always


- name: "Drop: {{container_name}}"
  shell: "podman stop -t 1800  {{container_name}} ; podman rm -f {{container_name}}"
  ignore_errors: true
  tags:
    - always

- name: "Drop: {{container_name}}"
  containers.podman.podman_container:
    name: "{{container_name}}"
    state: absent # this stops and removes the container
    stop_timeout: 180
  tags:
    - always

- name: Get timestamp from the system
  shell: "date +%Y-%m-%d%H-%M-%S"
  register: tstamp
  tags:
    - always
- name: Set variables
  set_fact:
    cur_date: "{{ tstamp.stdout[0:10]}}"
    cur_time: "{{ tstamp.stdout[10:]}}"
  tags:
    - always

- name: System timestamp - time
  debug:
    msg:  "Current date: {{ cur_time }}"
  tags:
    - always
```

**Comment by sshnaidm** [comment]
`stop_timeout` args is not supposed to be used in `absent`, it should be used in `started`, `created` etc and to set container to specific `stop_timeout`. And when we want to stop it, it will apply the configured `stop_timeout`
You can check what is the current stop timeout in `podman inspect my_container`

**Comment by sshnaidm** [comment]
```yaml
    - name: Run container with stop timeout
      containers.podman.podman_container:
        name: teststop
        image: alpine
        state: started
        command: sleep 1d
        stop_timeout: 12
```

```bash
$ podman inspect teststop | grep -i stoptime
               "StopTimeout": 12,

$ podman stop teststop
WARN[0012] StopSignal SIGTERM failed to stop container teststop in 12 seconds, resorting to SIGKILL 
teststop
```
