### ISSUE TITLE
Add support for targets in multi-stage builds

### ISSUE THREAD

**Issue by aknochow** [containers/ansible-podman-collections#631]
Requesting support for targets (--target) to be added to the image module for builds (https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_image_module.html).  

This is currently not a feature in the podman module and is necessary for building multi-stage images.

Example:
```
- name: Build image {{ build_image }} with podman
  containers.podman.podman_image:
    name: "{{ build_image }}"
    path: src/{{ clone_repo }}/{{ clone_branch }}
    build:
      target: eda-ui
  register: podman_build
  until: podman_build is not failed
  retries: 1
  delay: 10
```
  

That would do the same as a `podman build --target eda-ui` (using https://github.com/ansible/ansible-ui/blob/main/Dockerfile) as an example Containerfile.
