### ISSUE TITLE
containers.podman.podman_container (abd podman_pod) not idempotent with generate_systemd set.

### ISSUE THREAD

**Issue by kristvanbesien** [containers/ansible-podman-collections#645]
/kind bug

**Description**

When generating a systemd for a pod or container the playbook no longer is idempotent.

**Steps to reproduce the issue:**

1. Run a playbook that creates pods and containers.
 
2. Run it a second time.

**Describe the results you received:**

The podman_pod and podman_container tasks aslways return a status of changed.

**Describe the results you expected:**

The podman_pod and podman_container tasks aslways return a status of ok.

**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman             1.10.3
```
**Output of `ansible --version`:**

```
ansible [core 2.15.3]
  config file = /Users/krist/.ansible.cfg
  configured module search path = ['/Users/krist/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/krist/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.11/bin/ansible
  python version = 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)] (/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

**Output of `podman version`:**

```
podman version 4.6.2
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
- name: setup traefik
  hosts: billie
  remote_user: service

  tasks:
  
  - name: create a podman network
    containers.podman.podman_network:
      name: web
  
  - name: prepare directories for ingres config
    ansible.builtin.file:
      path: "{{ansible_user_dir}}/{{item}}"
      state: directory
    loop:
    - config/traefik
    - data/traefik/letsencrypt

  - name: copy traefik config
    ansible.builtin.copy:
      src: traefik/traefik.yaml
      dest: "{{ansible_user_dir}}/config/traefik"
        
  - name: create a pod for traefik
    containers.podman.podman_pod:
      name: ingress
      network:
        - web
      ports:
        - 80:80
        - 443:443
        - 8080:8080
        - 2222:2222
      generate_systemd:
        path: "{{ ansible_user_dir }}/.config/systemd/user/"
        restart_policy: always
 
  - name: create traefik container
    containers.podman.podman_container:
      name: traefik
      pod: ingress
      image: docker.io/library/traefik:latest
      security_opt: "label=type:container_runtime_t"
      generate_systemd:
        path: "{{ ansible_user_dir }}/.config/systemd/user/"
        restart_policy: always
      volumes:  
        - "{{ ansible_user_dir }}/data/traefik/letsencrypt:/letsencrypt:z"
        - "{{ ansible_user_dir }}/config/traefik/traefik.yaml:/etc/traefik/traefik.yaml:z"
        - "/run/user/{{ ansible_user_uid }}/podman/podman.sock:/var/run/docker.sock:z"
```

`ansible-playbook -i inventory --diff playbook.yml`

```
TASK [create a pod for traefik] ******************************************************************************************************************
--- before
+++ after
@@ -1 +1,2 @@
-systemd_container-traefik.service.service -
+systemd_container-traefik.service.service - BindsTo=pod-ingress.service
+After=pod-ingress.service

changed: [billie]

TASK [create traefik container] ******************************************************************************************************************
--- before
+++ after
@@ -1,2 +1 @@
-systemd_container-traefik.service.service - BindsTo=pod-ingress.service
-After=pod-ingress.service
+systemd_container-traefik.service.service -

changed: [billie]```
