### ISSUE TITLE
module 'podman_container'

### ISSUE THREAD

**Issue by tgerczei** [containers/ansible-podman-collections#7]
Shall the above module (previously seen in [TripleO-Ansible](https://github.com/openstack/tripleo-ansible/blob/master/tripleo_ansible/ansible_plugins/modules/podman_container.py)) be published here?

**Comment by sshnaidm** [comment]
@tgerczei sure, I'm going to add all modules from there, hopefully this weekend :)

**Comment by tgerczei** [comment]
@sshnaidm thanks, really looking forward to that!

**Comment by tgerczei** [comment]
Thanks! Can't wait to see this hit Galaxy.

**Comment by sshnaidm** [comment]
@tgerczei and all interested, modules were published (as is). Please feel free to report issues if you have such.
`ansible-galaxy collection install containers.podman`

```yaml
- name: Start podman container
  containers.podman.podman_container:
    name: test
    image: alpine
    command: sleep 1d

- name: Gather podman info
  containers.podman.podman_container_info: {}
  register: podman_containers
```
