### ISSUE TITLE
Env in container exec are wrongly double quoted

### ISSUE THREAD

**Issue by micheelengronne** [containers/ansible-podman-collections#714]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

ENV being forcibly double-quoted, it make the module impossible to use with process that require ENV with strict syntax.

The line inquestion is: https://github.com/containers/ansible-podman-collections/blob/efbfba7c3c4ed95bb75fcabfced61f650b28bac8/plugins/modules/podman_container_exec.py#L159

A possible way would be to add an option to avoid adding these double-quotes around the value and set it to false for retrocompatibility.

**Steps to reproduce the issue:**

For instance, trying to connect to a hashicorp Vault with VAULT_ADDR will fail with the golang error: 

    first path segment in URL cannot contain colon

**Comment by sshnaidm** [comment]
@micheelengronne I'm not sure I understand the problem, which exactly case it fails in?
Please provide any reproducing details - task, failure log and others.

**Comment by lestragon** [comment]
I had the same problem yesterday. I'm currently using the version 1.11.0

@sshnaidm In my case, i'm trying to log in to a software called trino using a environnement variable. The log in process fail because of the quotes added to the password.

Here is to example to reproduce
```YAML
    - name: Working by adding export variable first
      containers.podman.podman_container_exec:
        name: TRINO
        argv:
          - /bin/sh
          - -c
          - "export TRINO_PASSWORD='ADMIN'; \
             trino 'https://localhost:8443' --user EDH_ADMIN --password --insecure --execute 'show catalogs;'"
```

```YAML
    - name: Not working - Authentification failed
      containers.podman.podman_container_exec:
        name: TRINO
        argv:
          - /bin/sh
          - -c
          - trino 'https://localhost:8443' --user ADMIN --password --insecure --execute 'show catalogs;'
        env:
          TRINO_PASSWORD: ADMIN
```

Log of the failure :

> Failed to run ['podman', 'container', 'exec', '--env', 'TRINO_PASSWORD="ADMIN"', 'TRINO', '/bin/sh', '-c', "trino 'https://localhost:8443' --user ADMIN--password --insecure --execute 'show catalogs;'"] ['container', 'exec', '--env', 'TRINO_PASSWORD="ADMIN"', 'TRINO', '/bin/sh', '-c', "trino 'https://localhost:8443' --user ADMIN--password --insecure --execute 'show catalogs;'"]: Feb 23, 2024 1:31:30 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
Authentication failed: Access Denied: **Invalid credentials**

A simpler way to see this 
```YAML
    - name: Hello World
      containers.podman.podman_container_exec:
        name: alpine
        argv:
          - /bin/sh
          - -c
          - echo "Hello $WORLD"
        env:
          WORLD: World
```
Will produce the result `Hello "World"`
