### ISSUE TITLE
`podman_container`: using YAML dictionaries for options in the `secrets` parameter

### ISSUE THREAD

**Issue by ivanov17** [containers/ansible-podman-collections#758]
/kind feature

**Description**

Hello, Sergey! What do you think about using list (or dictionary) of dictionaries in addition to using a list of strings for the `secrets` parameter in the `containers.podman.podman_container` module?

It might look like this:

```yaml
- containers.podman.podman_container:
    ...
    secrets:
      - secret: my_file
        type: mount
        target: /run/secrets/file.txt
        uid: 101
        mode: 0600
      - secret: my_variable
        type: env
        target: MY_VARIABLE
    ...
```

Or like this:

```yaml
- containers.podman.podman_container:
    ...
    secrets:
      my_file:
        type: mount
        target: /run/secrets/file.txt
        uid: 101
        mode: 0600
      my_variable:
        type: env
        target: MY_VARIABLE
    ...
```

It seems to be a little more readable than this:

```yaml
- containers.podman.podman_container:
    ...
    secrets:
      - "my_file,type=mount,target=/run/secrets/file.txt,uid=101,mode=0600"
      - "my_variable,type=env,target=MY_VARIABLE"
    ...
```
Also, if multiple Jinja variables are used in a string, it becomes too long.
