### ISSUE TITLE
Volumes idempotency breaks because of trailing and double slashes

### ISSUE THREAD

**Issue by sshnaidm** [containers/ansible-podman-collections#77]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If you provide volumes with double or trailing slashes, the volumes idempotency doesn't work.

**Steps to reproduce the issue:**

1.

```yaml
    - name: Install Graphite container
      containers.podman.podman_container:
        image: "graphiteapp/graphite-statsd"
        name: graphite
        volumes:
          - /tmp/test/:/data
        state: present

    - name: Install Graphite container
      containers.podman.podman_container:
        image: "graphiteapp/graphite-statsd"
        name: graphite
        volumes:
          - /tmp//test/:/data/
        state: present
```

**Describe the results you received:**
Container is recreated

**Describe the results you expected:**
Container is not recreated.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**
