### ISSUE TITLE
idempotency broken with command in podman_container

### ISSUE THREAD

**Issue by rkozlo** [containers/ansible-podman-collections#799]
/kind bug

Command in container breaks converge/idempotency tests
Updated from 1.10.3 to 1.15.3 and after that molecule is not passing. As i can see it is releated with `command` field in container. Deleting this parameter from task not helping once container is already created.
Task:
```
- name: task
  containers.podman.podman_container:
    name: "test"
    image: "img:stage"
    state: created
    read_only: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/containers/:/var/lib/containers:ro
      - /dev/disk/:/dev/disk:ro
    publish: "{{ port_app }}:{{ port_publish }}"
    cpus: 1
    memory: "{{ mem_limit }}"
    detach: true
    privileged: true
    device: /dev/kmsg
    recreate: false
    command: "{{ running_options }}"
    generate_systemd:
      container_prefix: prefix
      path: "/etc/systemd/system/"
      after:
        - "podman.service"
        - "network.target"
      requires:
        - "podman.service"
      restart_policy: on-failure
      restart_sec: 5
```

1.Run task first time

2.Second time the same task ends with error

**Describe the results you received:**
Error i am getting
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [instance]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1720706220.3119345-124409-269658419801838/AnsiballZ_podman_container.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1720706220.3119345-124409-269658419801838/AnsiballZ_podman_container.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1720706220.3119345-124409-269658419801838/AnsiballZ_podman_container.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.containers.podman.plugins.modules.podman_container', init_globals=dict(_module_fqn='ansible_collections.containers.podman.plugins.modules.podman_container', _modlib_path=modlib_path),\r\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_fi3xsla7/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1377, in <module>\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_fi3xsla7/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/modules/podman_container.py\", line 1372, in main\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_fi3xsla7/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py\", line 1880, in execute\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_fi3xsla7/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py\", line 1807, in make_created\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_fi3xsla7/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py\", line 1542, in different\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_fi3xsla7/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py\", line 1463, in is_different\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_fi3xsla7/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/podman_container_lib.py\", line 1431, in diffparam_volume\r\n  File \"/tmp/ansible_containers.podman.podman_container_payload_fi3xsla7/ansible_containers.podman.podman_container_payload.zip/ansible_collections/containers/podman/plugins/module_utils/podman/common.py\", line 366, in createcommand\r\nIndexError: list index out of range\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Describe the results you expected:**
Passing

**Additional information you deem important (e.g. issue happens only occasionally):**
Tested version and crashing since 1.14.0
Runing without `command` parameter task and idempotency test passes
Once added command and container is created it constantly throws this error

Version of the `containers.podman` collection: 1.15.3 - probably broken since 1.14.0
Collection used in molecule:
- community.general-9.1.0
- containers.podman-1.15.3

**Output of `ansible --version`:**
```
ansible [core 2.14.0]
python version = 3.9.19
jinja version = 3.1.4
libyaml = True
```

**Output of `podman version`:**

vagrant + almalinux9 + package install podman

**Output of `podman info --debug`:**

vagrant + almalinux9 + package install podman

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

vagrant + almalinux9 + package install podman

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

Standard molecule converge
