### ISSUE TITLE
Multiple networks not supported (such as ipvlan)

### ISSUE THREAD

**Issue by Firstyear** [containers/ansible-podman-collections#824]
https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html

Reading your documentation, it appears not possible to create multiple networks.

Neither does it appear possible to use advanced features like ipvlan.

If it is possible, can these be documented with appropriate examples?

If it is not possible, can the feature be added to support multiple networks on a single container (such as two ipvlan connections).

**Comment by sshnaidm** [comment]
Well, podman networks are created and documented in [`podman_network`](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_network_module.html) module, not in podman container. See [`net_config`](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_network_module.html#parameter-net_config) option, it allows configuration multiple subnets and gateways in same network.
Here is the example of `ipvlan` network:
```yaml
    - name: Create ipvlan network
      containers.testpodman.podman_network:
        name: net-ipvlan
        state: present
        driver: ipvlan
        net_config:
          - subnet: 10.12.0.0/16
            gateway: 10.12.0.1
            ip_range: 10.12.111.0/24
```
After you create networks you can attach Podman container to them.

**Comment by Firstyear** [comment]
You misunderstand. In ansible docker you can do:

```
- name: Create avahi container
  docker_container:
    name: avahi
   ...
    networks:
      - name: ipvlan_1
        ipv4_address: 10.1.0.1
        ipv6_address: "..."
      - name: ipvlan_2
        ipv4_address: 10.2.0.2
        ipv6_address: "..."
      - name: ipvlan_3
        ipv4_address: 10.3.0.3
        ipv6_address: "..."
```

Where as the podman_container equivalent can't do this (Or at least, reading the documentation for podman_container, it is not possible to do this).

So if it is possible, can it be documented clearly with examples?
