### ISSUE TITLE
Support git repository contexts with `podman_image` build

### ISSUE THREAD

**Issue by bmenant** [containers/ansible-podman-collections#825]
/kind feature

**Description**

Being able to use a git repository as a path (build context) when building images.

https://docs.podman.io/en/latest/markdown/podman-build.1.html#building-an-image-using-a-git-repository

```yaml
- containers.podman.podman_image:
    name: my-image
    path: "git@github.com:bmenant/repo-with-containerfile.git"
    state: build
```

**Comment by mhjacks** [comment]
This worked for me on collection version 1.16.1:

```yaml
---
- name: Test build
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Build image
      containers.podman.podman_image:
        state: build
        path: https://github.com/containers/PodmanHello.git
        name: hello
```
