### ISSUE TITLE
quadlet module ignores the groups parameter when generating container unit file

### ISSUE THREAD

**Issue by djlongy** [containers/ansible-podman-collections#844]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Ansible containers.podman.podman_container module ignores the groups parameter when generating a quadlet unit file.

**Steps to reproduce the issue:**
1. Running the following task
```yaml
- name: Create Quadlet container file {{ item.name }}
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: quadlet
    quadlet_dir: "/home/{{ container_svc }}/.config/containers/systemd"
    command: "{{ item.command | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    network: "{{ item.networks[0].name | default(omit) }}"
    add_hosts: "{{ item.extra_hosts | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    env_file: "{{ item.env_file | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
  become_user: "{{ container_svc }}"
  become: true
```

**Describe the results you received:**
The following file is generated
```ini
[Container]
ContainerName=promtail-1
Exec=-config.file=/mnt/config/promtail-config.yaml
HostName=promtail-1
Image=docker.io/grafana/promtail:main
Network=localprom
Volume=/opt/promtail/config:/mnt/config
Volume=/var/log:/var/log
PodmanArgs=--add-host loki:192.168.10.51
```

**Describe the results you expected:**

```ini
[Container]
ContainerName=promtail-1
Exec=-config.file=/mnt/config/promtail-config.yaml
HostName=promtail-1
Image=docker.io/grafana/promtail:main
Network=localprom
Volume=/opt/promtail/config:/mnt/config
Volume=/var/log:/var/log
PodmanArgs=--add-host loki:192.168.10.51
GroupAdd=995 1001 1002
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Repeatable

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman: 1.15.4
```

**Output of `ansible --version`:**

```
ansible [core 2.16.10]
  python version = 3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)] 
  jinja version = 3.1.4
  libyaml = True
```

**Output of `podman version`:**

```
podman version 4.9.4-rhel
```

**Output of `podman info --debug`:**

``` yaml
host:
  arch: amd64
  buildahVersion: 1.33.8
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: fb8c4bf50dbc044a338137871b096eea8041a1fa'
  cpuUtilization:
    idlePercent: 98.94
    systemPercent: 0.36
    userPercent: 0.71
  cpus: 2
  databaseBackend: sqlite
  distribution:
    distribution: rhel
    version: "9.4"
  eventLogger: journald
  freeLocks: 2011
  hostname: podman03
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 991
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 995
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 5.14.0-427.13.1.el9_4.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 3389210624
  memTotal: 8058425344
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-3.el9_4.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark-1.10.3-1.el9.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun-1.14.3-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.3
      commit: 1961d211ba98f532ea52d2e80f4c20359f241a98
      rundir: /run/user/995/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: false
    path: /run/user/995/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.3-1.el9.x86_64
    version: |-
      slirp4netns version 1.2.3
      commit: c22fde291bb35b354e6ca44d13be181c76a0a432
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 1073737728
  swapTotal: 1073737728
  uptime: 40h 43m 40.00s (Approximately 1.67 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/svc_podman/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 6
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/svc_podman/.local/share/containers/storage
  graphRootAllocated: 4227858432
  graphRootUsed: 2429411328
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 11
  runRoot: /tmp/containers-user-995/containers
  transientStore: false
  volumePath: /home/svc_podman/.local/share/containers/storage/volumes
version:
  APIVersion: 4.9.4-rhel
  Built: 1723107101
  BuiltTime: Thu Aug  8 18:51:41 2024
  GitCommit: ""
  GoVersion: go1.21.11 (Red Hat 1.21.11-1.el9_4)
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.4-rhel```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.9.4-10.el9_4.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
vars
  - name: "promtail-1"
    image: "docker.io/grafana/promtail:{{ promtail_version }}"
    volumes:
      - "{{ base_dir }}/promtail/config:/mnt/config"
      - /var/log:/var/log
    extra_hosts:
      loki: "{{ ansible_host }}"
    links:
        - "loki"
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - name: localprom
    hostname: "promtail-1"
    aliases:
      - "promtail-1"
    restart_policy: always
    groups:
      - 1001
      - 995
      - 1000

task
- name: Create Quadlet container file {{ item.name }}
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: quadlet
    quadlet_dir: "/home/{{ container_svc }}/.config/containers/systemd"
    command: "{{ item.command | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    network: "{{ item.networks[0].name | default(omit) }}"
    add_hosts: "{{ item.extra_hosts | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    env_file: "{{ item.env_file | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
  become_user: "{{ container_svc }}"
  become: true
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```yaml
changed: [podman01] => (item={'name': 'promtail-1', 'image': 'docker.io/grafana/promtail:main', 'volumes': ['/opt/promtail/config:/mnt/config', '/var/log:/var/log'], 'extra_hosts': {'loki': '192.168.10.51'}, 'links': ['loki-1'], 'command': '-config.file=/mnt/config/promtail-config.yaml', 'networks': [{'name': 'localprom'}], 'hostname': 'promtail-1', 'aliases': ['promtail-1'], 'restart_policy': 'always', 'groups': [1001]}) => changed=true
  ansible_loop_var: container_item
  container_item:
    aliases:
    - promtail-1
    command: -config.file=/mnt/config/promtail-config.yaml
    extra_hosts:
      loki: 192.168.10.51
    groups:
    - 1001
    - 995
    - 1000
    hostname: promtail-1
    image: docker.io/grafana/promtail:main
    links:
    - loki-1
    name: promtail-1
    networks:
    - name: localprom
    restart_policy: always
    volumes:
    - /opt/promtail/config:/mnt/config
    - /var/log:/var/log
  enabled: true
  name: promtail-1
  state: started
  status:
    ActiveEnterTimestampMonotonic: '0'
    ActiveExitTimestampMonotonic: '0'
    ActiveState: inactive
    After: var.mount -.mount run-user-995.mount app.slice basic.target opt.mount
    AllowIsolate: 'no'
    AssertResult: 'no'
    AssertTimestampMonotonic: '0'
    Before: shutdown.target
    BlockIOAccounting: 'no'
    BlockIOWeight: '[not set]'
    CPUAccounting: 'yes'
    CPUAffinityFromNUMA: 'no'
    CPUQuotaPerSecUSec: infinity
    CPUQuotaPeriodUSec: infinity
    CPUSchedulingPolicy: '0'
    CPUSchedulingPriority: '0'
    CPUSchedulingResetOnFork: 'no'
    CPUShares: '[not set]'
    CPUUsageNSec: '[not set]'
    CPUWeight: '[not set]'
    CacheDirectoryMode: '0755'
    CanFreeze: 'yes'
    CanIsolate: 'no'
    CanReload: 'no'
    CanStart: 'yes'
    CanStop: 'yes'
    CapabilityBoundingSet: cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend cap_audit_read cap_perfmon cap_bpf cap_checkpoint_restore
    CleanResult: success
    CollectMode: inactive
    ConditionResult: 'no'
    ConditionTimestampMonotonic: '0'
    ConfigurationDirectoryMode: '0755'
    Conflicts: shutdown.target
    ControlGroupId: '0'
    ControlPID: '0'
    CoredumpFilter: '0x33'
    DefaultDependencies: 'yes'
    DefaultMemoryLow: '0'
    DefaultMemoryMin: '0'
    Delegate: 'yes'
    DelegateControllers: cpu cpuacct cpuset io blkio memory devices pids bpf-firewall bpf-devices bpf-foreign bpf-socket-bind bpf-restrict-network-interfaces
    Description: promtail-1.service
    DevicePolicy: auto
    DynamicUser: 'no'
    Environment: PODMAN_SYSTEMD_UNIT=promtail-1.service
    ExecMainCode: '0'
    ExecMainExitTimestampMonotonic: '0'
    ExecMainPID: '0'
    ExecMainStartTimestampMonotonic: '0'
    ExecMainStatus: '0'
    ExecStart: '{ path=/usr/bin/podman ; argv[]=/usr/bin/podman run --name=promtail-1 --cidfile=/run/user/995/promtail-1.cid --replace --rm --cgroups=split --network=localprom --sdnotify=conmon -d -v /opt/promtail/config:/mnt/config -v /var/log:/var/log --hostname promtail-1 --add-host loki:192.168.10.51 docker.io/grafana/promtail:main -config.file=/mnt/config/promtail-config.yaml ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }'
    ExecStartEx: '{ path=/usr/bin/podman ; argv[]=/usr/bin/podman run --name=promtail-1 --cidfile=/run/user/995/promtail-1.cid --replace --rm --cgroups=split --network=localprom --sdnotify=conmon -d -v /opt/promtail/config:/mnt/config -v /var/log:/var/log --hostname promtail-1 --add-host loki:192.168.10.51 docker.io/grafana/promtail:main -config.file=/mnt/config/promtail-config.yaml ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }'
    ExecStop: '{ path=/usr/bin/podman ; argv[]=/usr/bin/podman rm -v -f -i --cidfile=/run/user/995/promtail-1.cid ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }'
    ExecStopEx: '{ path=/usr/bin/podman ; argv[]=/usr/bin/podman rm -v -f -i --cidfile=/run/user/995/promtail-1.cid ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }'
    ExecStopPost: '{ path=/usr/bin/podman ; argv[]=/usr/bin/podman rm -v -f -i --cidfile=/run/user/995/promtail-1.cid ; ignore_errors=yes ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }'
    ExecStopPostEx: '{ path=/usr/bin/podman ; argv[]=/usr/bin/podman rm -v -f -i --cidfile=/run/user/995/promtail-1.cid ; flags=ignore-failure ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }'
    ExitType: main
    FailureAction: none
    FileDescriptorStoreMax: '0'
    FinalKillSignal: '9'
    FragmentPath: /run/user/995/systemd/generator/promtail-1.service
    FreezerState: running
    GID: '[not set]'
    GuessMainPID: 'yes'
    IOAccounting: 'no'
    IOReadBytes: '18446744073709551615'
    IOReadOperations: '18446744073709551615'
    IOSchedulingClass: '2'
    IOSchedulingPriority: '4'
    IOWeight: '[not set]'
    IOWriteBytes: '18446744073709551615'
    IOWriteOperations: '18446744073709551615'
    IPAccounting: 'no'
    IPEgressBytes: '[no data]'
    IPEgressPackets: '[no data]'
    IPIngressBytes: '[no data]'
    IPIngressPackets: '[no data]'
    Id: promtail-1.service
    IgnoreOnIsolate: 'no'
    IgnoreSIGPIPE: 'yes'
    InactiveEnterTimestampMonotonic: '0'
    InactiveExitTimestampMonotonic: '0'
    JobRunningTimeoutUSec: infinity
    JobTimeoutAction: none
    JobTimeoutUSec: infinity
    KeyringMode: inherit
    KillMode: mixed
    KillSignal: '15'
    LimitAS: infinity
    LimitASSoft: infinity
    LimitCORE: infinity
    LimitCORESoft: '0'
    LimitCPU: infinity
    LimitCPUSoft: infinity
    LimitDATA: infinity
    LimitDATASoft: infinity
    LimitFSIZE: infinity
    LimitFSIZESoft: infinity
    LimitLOCKS: infinity
    LimitLOCKSSoft: infinity
    LimitMEMLOCK: '8388608'
    LimitMEMLOCKSoft: '8388608'
    LimitMSGQUEUE: '819200'
    LimitMSGQUEUESoft: '819200'
    LimitNICE: '0'
    LimitNICESoft: '0'
    LimitNOFILE: '524288'
    LimitNOFILESoft: '1024'
    LimitNPROC: '30573'
    LimitNPROCSoft: '30573'
    LimitRSS: infinity
    LimitRSSSoft: infinity
    LimitRTPRIO: '0'
    LimitRTPRIOSoft: '0'
    LimitRTTIME: infinity
    LimitRTTIMESoft: infinity
    LimitSIGPENDING: '30573'
    LimitSIGPENDINGSoft: '30573'
    LimitSTACK: infinity
    LimitSTACKSoft: '8388608'
    LoadState: loaded
    LockPersonality: 'no'
    LogLevelMax: '-1'
    LogRateLimitBurst: '0'
    LogRateLimitIntervalUSec: '0'
    LogsDirectoryMode: '0755'
    MainPID: '0'
    ManagedOOMMemoryPressure: auto
    ManagedOOMMemoryPressureLimit: '0'
    ManagedOOMPreference: none
    ManagedOOMSwap: auto
    MemoryAccounting: 'yes'
    MemoryAvailable: infinity
    MemoryCurrent: '[not set]'
    MemoryDenyWriteExecute: 'no'
    MemoryHigh: infinity
    MemoryLimit: infinity
    MemoryLow: '0'
    MemoryMax: infinity
    MemoryMin: '0'
    MemorySwapMax: infinity
    MountAPIVFS: 'no'
    NFileDescriptorStore: '0'
    NRestarts: '0'
    NUMAPolicy: n/a
    Names: promtail-1.service
    NeedDaemonReload: 'no'
    Nice: '0'
    NoNewPrivileges: 'no'
    NonBlocking: 'no'
    NotifyAccess: all
    OOMPolicy: continue
    OOMScoreAdjust: '200'
    OnFailureJobMode: replace
    OnSuccessJobMode: fail
    Perpetual: 'no'
    PrivateDevices: 'no'
    PrivateIPC: 'no'
    PrivateMounts: 'no'
    PrivateNetwork: 'no'
    PrivateTmp: 'no'
    PrivateUsers: 'no'
    ProcSubset: all
    ProtectClock: 'no'
    ProtectControlGroups: 'no'
    ProtectHome: 'no'
    ProtectHostname: 'no'
    ProtectKernelLogs: 'no'
    ProtectKernelModules: 'no'
    ProtectKernelTunables: 'no'
    ProtectProc: default
    ProtectSystem: 'no'
    RefuseManualStart: 'no'
    RefuseManualStop: 'no'
    ReloadResult: success
    ReloadSignal: '1'
    RemainAfterExit: 'no'
    RemoveIPC: 'no'
    Requires: app.slice basic.target
    RequiresMountsFor: /opt/promtail/config /var/log /run/user/995/containers
    Restart: 'no'
    RestartKillSignal: '15'
    RestartUSec: 100ms
    RestrictNamespaces: 'no'
    RestrictRealtime: 'no'
    RestrictSUIDSGID: 'no'
    Result: success
    RootDirectoryStartOnly: 'no'
    RuntimeDirectoryMode: '0755'
    RuntimeDirectoryPreserve: 'no'
    RuntimeMaxUSec: infinity
    RuntimeRandomizedExtraUSec: '0'
    SameProcessGroup: 'no'
    SecureBits: '0'
    SendSIGHUP: 'no'
    SendSIGKILL: 'yes'
    Slice: app.slice
    SourcePath: /home/svc_podman/.config/containers/systemd/promtail-1.container
    StandardError: inherit
    StandardInput: 'null'
    StandardOutput: journal
    StartLimitAction: none
    StartLimitBurst: '5'
    StartLimitIntervalUSec: 10s
    StartupBlockIOWeight: '[not set]'
    StartupCPUShares: '[not set]'
    StartupCPUWeight: '[not set]'
    StartupIOWeight: '[not set]'
    StateChangeTimestampMonotonic: '0'
    StateDirectoryMode: '0755'
    StatusErrno: '0'
    StopWhenUnneeded: 'no'
    SubState: dead
    SuccessAction: none
    SyslogFacility: '3'
    SyslogIdentifier: promtail-1
    SyslogLevel: '6'
    SyslogLevelPrefix: 'yes'
    SyslogPriority: '30'
    SystemCallErrorNumber: '2147483646'
    TTYReset: 'no'
    TTYVHangup: 'no'
    TTYVTDisallocate: 'no'
    TasksAccounting: 'yes'
    TasksCurrent: '[not set]'
    TasksMax: '48916'
    TimeoutAbortUSec: 1min 30s
    TimeoutCleanUSec: infinity
    TimeoutStartFailureMode: terminate
    TimeoutStartUSec: 1min 30s
    TimeoutStopFailureMode: terminate
    TimeoutStopUSec: 1min 30s
    TimerSlackNSec: '50000'
    Transient: 'no'
    Type: notify
    UID: '[not set]'
    UMask: '0022'
    UnitFilePreset: disabled
    UnitFileState: generated
    UtmpMode: init
    WatchdogSignal: '6'
    WatchdogTimestampMonotonic: '0'
    WatchdogUSec: infinity
    WorkingDirectory: '!/home/svc_podman'
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
When running the same data on `containers.podman.podman_container` with `generate_systemd` parameter, it honors the groups configuration and adds it to the systemd unit file. see below.
```yaml
- name: Generate systemd service unit file for "{{ item.name }}"
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: created
    generate_systemd:
      names: true
      new: true
      container_prefix: container
      path: "/home/{{ container_svc }}/.config/systemd/user"
      restart_policy: "{{ item.restart_policy | default('always') }}"
    rm: false
    cmd_args: 
    command: "{{ item.command | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    network: "{{ item.networks[0].name | default(omit) }}"
    add_hosts: "{{ item.extra_hosts | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    env_file: "{{ item.env_file | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
  become_user: "{{ container_svc }}"
  become: true
```

```ini
# container-promtail-1.service
# autogenerated by Podman 4.9.4-rhel
# Wed Sep 11 17:55:10 AEST 2024

[Unit]
Description=Podman container-promtail-1.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=%t/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=always
TimeoutStopSec=70
ExecStart=/usr/bin/podman container run \
	--cidfile=%t/%n.ctr-id \
	--cgroups=no-conmon \
	--rm \
	--sdnotify=conmon \
	-d \
	--replace \
	--name promtail-1 \
	--network localprom \
	--hostname promtail-1 \
	--add-host loki:192.168.10.51 \
	--group-add 1001 \
	--group-add 995 \
	--group-add 1000 \
	--volume /opt/promtail/config:/mnt/config \
	--volume /var/log:/var/log docker.io/grafana/promtail:main \
	-config.file=/mnt/config/promtail-config.yaml
ExecStop=/usr/bin/podman stop \
	--ignore -t 10 \
	--cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm \
	-f \
	--ignore -t 10 \
	--cidfile=%t/%n.ctr-id
Type=notify
NotifyAccess=all
```
