### ISSUE TITLE
Quadlet example in documentation uses unsupported pull policy

### ISSUE THREAD

**Issue by InsideTheVoid** [containers/ansible-podman-collections#861]
The quadlet example on [Ansible Community Documentation](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html) uses `Pull=true` which is not supported.

```yaml
- name: Create a Quadlet file
  containers.podman.podman_container:
    name: quadlet-container
    image: nginx
    state: quadlet
    quadlet_filename: custome-container
    device: "/dev/sda:/dev/xvda:rwm"
    ports:
      - "8080:80"
    volumes:
      - "/var/www:/usr/share/nginx/html"
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=true"
      - |
        [Install]
        WantedBy=default.target
```
Podman reports `Error: unsupported pull policy "true"`.

The example should be changed to one of these choices:
- `"missing"`
- `"always"`
- `"never"`
- `"newer"`
