### ISSUE TITLE
podman_container quadlet downloads image in checkrun

### ISSUE THREAD

**Issue by mstinsky** [containers/ansible-podman-collections#876]
As the title stats. 
When using podman_container with state quadlet and running in check mode the module downloads the image defined in the ansible task.
A checkrun should not do that and only show the quadlet file that is rendered.

Simple test:
```
- name: Test nginx
  containers.podman.podman_container:
    state: quadlet
    name: nginx-test
    image: docker.io/nginx:latest
```

Before running the task check podman images that shows the image does not exist.
Running the task in check mode shows:
```
TASK [test : Test nginx] ******************************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -1 +1,4 @@
+[Container]
+ContainerName=nginx-test
+Image=docker.io/nginx:latest
```

`/etc/containers/systemd` does not have the quadlet file as expected but the image was downloaded:
```
podman images | grep nginx
docker.io/library/nginx                                    latest               3b25b682ea82  5 weeks ago    196 MB
```
