### ISSUE TITLE
Idempotent issue related to latest podman version

### ISSUE THREAD

**Issue by Macleykun** [containers/ansible-podman-collections#885]
I'm using the following versions related to the playbook:
```
podman-5.3.1-1.fc42.x86_64
ansible-collection-containers-podman-1.12.0-6.fc41.noarch
ansible-core-2.18.0-1.fc42.noarch
```

I noticed when i run the following task:
```yaml
    - name: Setup crafty container
      containers.podman.podman_container:
        name: crafty
        image: registry.gitlab.com/crafty-controller/crafty-4:latest
        publish:
          - "8999:8443" # HTTPS
          - "8123:8123" # DYNMAP
          - "19133:19132/udp" # BEDROCK
          - "27500-27600:25500-25600" # MC SERV PORT RANGE
        labels:
          io.containers.autoupdate: registry
          PODMAN_SYSTEMD_UNIT: pod-crafty.service
        env: TZ=Etc/UTC
        state: created
        rm: true
        volumes:
          - "/home/{{ rootless_usr.name }}/container_files/crafty/backups:/crafty/backups:Z"
          - "/home/{{ rootless_usr.name }}/container_files/crafty/logs:/crafty/logs:Z"
          - "/home/{{ rootless_usr.name }}/container_files/crafty/servers:/crafty/servers:Z"
          - "/home/{{ rootless_usr.name }}/container_files/crafty/config:/crafty/app/config:Z"
          - "/home/{{ rootless_usr.name }}/container_files/crafty/import:/crafty/import:Z"
      become_user: "{{ rootless_usr.name }}"
      notify: Restart Crafty
```

I see that it's always changed:
```
TASK [Setup crafty container] *************************************************************************************************************************
--- before
+++ after
@@ -1,2 +1,2 @@
-network - pasta
-restart_policy - no:0
+network - default
+restart_policy - :0

changed: [node.name.io]
```

This is all done locally and i notice this with other containers aswell, is this something due to the change of the network driver in podman being changed into pasta?

It's not immediatly an issue as i use this within a hobby project, but i can imagine based on the changed state, you would restart the container so it uses the newer image. But if nothing really changed, then it would unexpectedly reboot the container.

Curious if this is something you also see on your end! We use: Fedora release 42 (Rawhide) which is experimental i just noticed.. not sure if this is the reason.
