### ISSUE TITLE
podman_container always pulling image

### ISSUE THREAD

**Issue by rkozlo** [containers/ansible-podman-collections#888]
Version: 1.6.2
Seems like this module is always pulling image.
Tried settings like:
```
state: absent
rmi: true
pull: never
```
Testing with molecule. Simple tasks like like:
```
- name: image
  containers.podman.podman_image:
    name: "zabbix/zabbix-agent2"
    tag: "{{ tag }}"
    state: "absent"
    force: "false"

- name: container
  containers.podman.podman_container:
    name: "container"
    image: "zabbix/zabbix-agent2:{{ tag }}"
    state: absent
    pull: never
    rmi: true
```
isn't idempotent. podman_image is deleting image and podman_container is pulling image with status changed: false
```
TASK [podman : debug] **********************************************************
ok: [molecule-podman-alma9-2] => 
  __status:
    actions:
    - pulled zabbix-agent2:latest
    changed: false
    container: {}
    failed: false
    podman_actions: []

```
