### ISSUE TITLE
podman_container: Missing systemd unit dependency settings like PartOf, BindsTo, and friends

### ISSUE THREAD

**Issue by phess** [containers/ansible-podman-collections#890]
The `podman_container` module currently offers the `wants` and `requires` parameters (which are converted to `Wants=` and `Requires=` within the generated systemd unit file).

In addition to `Wants=` and `Requires=`, [systemd offers](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#%5BUnit%5D%20Section%20Options) `PartOf=` and `BindsTo=` as well as a bunch of other unit dependency options.

This issue here is for adding the ability to define these systemd unit parameters via the `podman_container` parameter, just like the existing `wants` and `requires` module parameters already do.

Why this is useful:

* `PartOf=`:
When creating a container that will be part of a service, it's interesting to be able to stop/start/restart all services within said service with a single `systemctl` command, e.g.
~~~
$ systemctl --user stop myservice.target
$ systemctl --user start myservice.target
$ systemctl --user restart myservice.target
~~~

* `BindsTo=`:
If my service is made up of an application container (defined in `myapp.service`) and a database container (defined in `mydb.service`), I want to always stop the application if the container stops. This is accomplished by setting `BindsTo=mydb.service` ([docs](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#BindsTo=)) in the `[Unit]` section of `myapp.service`, ideally with `After=mydb.service` as well.

* Other dependency options:
I personally don't have a use for the other systemd unit dependency options in containers at the moment, but there may certainly be a case to be made for them as well.

**Comment by sshnaidm** [comment]
Hi, @phess 
I use Podman supported keys, which you can pass to the Podman itself, it's:
[```Currently, only the Alias, WantedBy and RequiredBy keys are supported```](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#enabling-unit-files)
Keep in mind that systemd feature is deprecated and probably will be removed in 6 version. Podman is pushing to `Quadlet` usage, which I support in a collection. When using Quadlet you can just add any part of systemd file to the quadlet file and it will be added to a systemd file. For example:
```yaml
- name: Create a Quadlet file
  containers.podman.podman_container:
    name: quadlet-container
    image: nginx
    state: quadlet
    quadlet_filename: custome-container
    quadlet_file_mode: '0640'
    device: "/dev/sda:/dev/xvda:rwm"
    ports:
      - "8080:80"
    volumes:
      - "/var/www:/usr/share/nginx/html"
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |
        [Install]
        WantedBy=default.target
        After=mydb.service
```
and so on, just add your settings in `quadlet_options`.
