### ISSUE TITLE
Creating a container with an environment variable containg "MAX_SIZE" is not idempotent

### ISSUE THREAD

**Issue by Popkornium18** [containers/ansible-podman-collections#892]
Example:

```
---
- hosts: localhost
  tasks:
    - containers.podman.podman_container:
        name: nginx
        image: docker.io/nginx:latest
        env:
          THIS_IS_THE_MAX_SIZE: 9001
```

When this is executed with `--check --diff` we can see this output:

```
--- before
+++ after
@@ -1 +1 @@
-env - this_is_the_max_size=9001
+env - this_is_the_max-size=9001
```

This issue was introduced in https://github.com/containers/ansible-podman-collections/pull/862
