### ISSUE TITLE
podman_login module hangs when using authfile

### ISSUE THREAD

**Issue by dustin1530** [containers/ansible-podman-collections#895]
Using the containers.podman.podman_login module to log into my registry, using an auth file that was created on the target machine hangs. However, it appears the login does succeed. Here is are my tasks:

```yaml
- name: Set base64 encoded user:password string
  set_fact:
    artifactory_user_passwd_string: "{{ (user + ':' + password) | b64encode }}"

- name: Create persistent registry login and login into registry
  block:
    - name: Create directory
      ansible.builtin.file:
        path: /root/.config/containers
        state: directory
        mode: '0755'

    - name: Create auth.json file
      ansible.builtin.template:
        src: auth.json.j2
        dest: /root/.config/containers/auth.json
        mode: '0600'
        owner: root
        group: root

    - name: Log into private container registry
      containers.podman.podman_login:
        authfile: /root/.config/containers/auth.json
      tags: login
```
Then here is the auth.conf.j2 template
```
{
  "auths": {
    "{{ registry }}": {
      "auth": "{{ artifactory_user_passwd_string }}"
    }
  }
}
```

On the target machine I see the auth file is created and does work when using this manually, via `podman login --authfile /root/.config/containers/auth.json`

ansible version info
```bash
# ansible --version
ansible [core 2.14.18]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.21 (main, Dec  4 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
