### ISSUE TITLE
service file is only updated after the second run

### ISSUE THREAD

**Issue by Macleykun** [containers/ansible-podman-collections#906]
Hi, i've updated to `ansible-collection-containers-podman-1.16.3-7.fc41.noarch` and noticed that our service files weren't updated when we were debuggin a container.

Here are the relevant tasks, but i'm sure if you replace the image with a generic ubuntu image you get the same:
```yaml
    - name: Setup jitstreamer-eb container
      containers.podman.podman_container:
        name: jitstreamer-eb
        network: caddy_network
        image: ghcr.io/jkcoxson/jitstreamer-eb:master
        cap_add: NET_ADMIN
        device: /dev/net/tun:/dev/net/tun
        publish:
          - "9172:9172"
          - "51869:51869/udp"
          - "9999:9999"
        expose: # TODO for Wes, expose through caddy or nah? I assume nah so remove this part if so
          - '9172'
          - 51869/udp
        labels:
          io.containers.autoupdate: registry
          PODMAN_SYSTEMD_UNIT: pod-jitstreamer-eb.service
        env:
          RUST_LOG: log
          WIREGUARD_ENDPOINT: "jitstreamer-de.jkcoxson.com"
          RUNNER_COUNT: 20
        state: created
        rm: true
        volumes:
        - "/mnt/datadisk1/container_files/jitstreamer-eb/data/jitstreamer.db:/app/jitstreamer.db:Z"
        - jitstreamer-lockdown:/var/lib/lockdown
        - jitstreamer-wireguard:/etc/wireguard
        generate_systemd:
          container_prefix: pod
          new: True
          no_header: True
          path: "/home/{{ rootless_usr.name }}/.config/systemd/user"
          restart_policy: always
      become_user: "{{ rootless_usr.name }}"
      notify: Restart jitstreamer-eb

#    - name: Generate systemd unit file for jitstreamer-eb container
#      containers.podman.podman_generate_systemd:
#        name: jitstreamer-eb
#        restart_policy: "always"
#        container_prefix: "pod"
#        new: true
#        restart_sec: 10
#        dest: "/home/{{ rootless_usr.name }}/.config/systemd/user"
#        no_header: true
#      become_user: "{{ rootless_usr.name }}"
#      notify: Restart jitstreamer-eb

    - name: Ensure jitstreamer-eb container is started and enabled
      ansible.builtin.systemd:
        name: pod-jitstreamer-eb
        daemon_reload: true
        state: started
        scope: "user"
        enabled: true
      become_user: "{{ rootless_usr.name }}"
      environment: # If you ever do systemctl stuff as the rootless user with containers, you must set that XDG variable so that you fix: Failed to connect to bus: No medium found, maybe good practise to put that export line into .bashrc mmm?
        XDG_RUNTIME_DIR: /run/user/{{rootless_usr.uid}}
      notify: Restart jitstreamer-eb
```

So i used to use the seperate task to generate the systemd but converted to use the builtin systemd_generate config when making the container.

Now between runs i only add/remove that publish part "9999:9999" and i notice the container tasks changes once (handler runs so it restarts the container with the old config), service file is still the same. Run it twice and the same happens but the service file is updated!

--- runs ---
I remove the entry 9999:
```bash
TASK [Setup jitstreamer-eb container] ***************************************************************************************************************************************************************
--- before
+++ after
@@ -1 +1 @@
-publish - 51869:51869/udp,9172:9172,9999:9999
+publish - 51869:51869/udp,9172:9172
```
service file still has 9999 in it.

running it another time.

```bash
TASK [Setup jitstreamer-eb container] ***************************************************************************************************************************************************************
--- before
+++ after
@@ -1,2 +1,2 @@
-publish - 51869:51869/udp,9172:9172,9999:9999
-systemd_pod-jitstreamer-eb.service.service -   --publish 9999:9999 \
+publish - 51869:51869/udp,9172:9172
+systemd_pod-jitstreamer-eb.service.service -
```

And indeed the service has changed!

Running it again shows nothing has changed.

I'm curious if you experience the same aswell, or if i'm making a mistake somewhere.
