### ISSUE TITLE
Unable to push image with containers.podman.podman_image:

### ISSUE THREAD

**Issue by sean-m-sullivan** [containers/ansible-podman-collections#910]
Having issue with pushing an image, recreated using the following

``` yaml
---
- name: Playbook to configure execution environments
  hosts: execution
  gather_facts: false
  connection: local
  vars_files:
    - "../vault.yml"
  tasks:

    - name: Pull builder images
      containers.podman.podman_image:
        name: quay.io/redhat_cop/instruqt_config_as_code:latest
        validate_certs: false
        force: true

    - name: Re-tag image
      containers.podman.podman_tag:
        image: quay.io/redhat_cop/instruqt_config_as_code
        target_names:
          - config_as_code

    - name: Push image to registry
      containers.podman.podman_image:
        name: config_as_code
        pull: false
        push: true
        username: "{{ ee_registry_username | default(omit, true) }}"
        password: "{{ ee_registry_password | default(omit, true) }}"
        tag: latest
        validate_certs: false
        push_args:
          dest: "{{ ee_registry_dest }}"
          compress: true

    - name: Add Execution Environment to controller
      ansible.builtin.include_role:
        name: infra.aap_configuration.execution_environments
      vars:
        controller_execution_environments:
          - image: "{{ aap_hostname }}/config_as_code"
            name: config_as_code
            pull: always
...

```

Get the following
```
TASK [Push image to registry] **********************************************************************************************************************************************************
task path: /home/lab-user/config_as_code_instruqt/testing/playbooks/pull_push_ee.yml:22
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: lab-user
<localhost> EXEC /bin/sh -c 'echo ~lab-user && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lab-user/.ansible/tmp `"&& mkdir "` echo /home/lab-user/.ansible/tmp/ansible-tmp-1741321509.5681596-70092-192151030392921 `" && echo ansible-tmp-1741321509.5681596-70092-192151030392921="` echo /home/lab-user/.ansible/tmp/ansible-tmp-1741321509.5681596-70092-192151030392921 `" ) && sleep 0'
Using module file /home/lab-user/.ansible/collections/ansible_collections/containers/podman/plugins/modules/podman_image.py
<localhost> PUT /home/lab-user/.ansible/tmp/ansible-local-699112fid2ns5/tmpn0j_xs2y TO /home/lab-user/.ansible/tmp/ansible-tmp-1741321509.5681596-70092-192151030392921/AnsiballZ_podman_image.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/lab-user/.ansible/tmp/ansible-tmp-1741321509.5681596-70092-192151030392921/ /home/lab-user/.ansible/tmp/ansible-tmp-1741321509.5681596-70092-192151030392921/AnsiballZ_podman_image.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/lab-user/.ansible/tmp/ansible-tmp-1741321509.5681596-70092-192151030392921/AnsiballZ_podman_image.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/lab-user/.ansible/tmp/ansible-tmp-1741321509.5681596-70092-192151030392921/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "actions": [
        "push --tls-verify=false --creds lab-user:******** --compress config_as_code:latest controller.tn9zq.sandbox2741.opentlc.com/config/config_as_code:latest"
    ],
    "changed": false,
    "invocation": {
        "module_args": {
            "arch": null,
            "auth_file": null,
            "build": {
                "annotation": null,
                "cache": true,
                "container_file": null,
                "extra_args": null,
                "file": null,
                "force_rm": false,
                "format": "oci",
                "rm": true,
                "target": null,
                "volume": null
            },
            "ca_cert_dir": null,
            "executable": "podman",
            "force": false,
            "name": "config_as_code",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "path": null,
            "pull": false,
            "pull_extra_args": null,
            "push": true,
            "push_args": {
                "compress": true,
                "dest": "controller.tn9zq.sandbox2741.opentlc.com/config",
                "extra_args": null,
                "format": null,
                "remove_signatures": null,
                "sign_by": null,
                "transport": null
            },
            "quadlet_dir": null,
            "quadlet_file_mode": null,
            "quadlet_filename": null,
            "quadlet_options": null,
            "state": "present",
            "tag": "latest",
            "username": "lab-user",
            "validate_certs": false
        }
    },
    "msg": "Failed to push image config_as_code:latest",
    "podman_actions": [
        "/usr/bin/podman image exists config_as_code:latest",
        "/usr/bin/podman inspect config_as_code:latest --format json",
        "/usr/bin/podman image ls config_as_code:latest --format json",
        "/usr/bin/podman inspect config_as_code:latest --format json",
        "/usr/bin/podman push --tls-verify=false --creds lab-user:******** --compress config_as_code:latest controller.tn9zq.sandbox2741.opentlc.com/config/config_as_code:latest"
    ],
    "stderr": "Getting image source signatures\nCopying blob sha256:2360a13c13c9c9297eb2cbf7d01264286d7c187695a73b0d0dab760b20697aa5\nCopying blob sha256:ba882ef1cbf49f70c6594693b63b1a6cfdaa44f503b8c716722034dd5f137148\nCopying blob sha256:ad5362eb8973710afa7450bf83d239791333ed21195b84118618dedc15e41c96\nCopying blob sha256:9ec1ffde9a92f68f7318ff81660992dac7883eb90dc5d9929871a428bbf3f8d1\nCopying blob sha256:534da5c014b89c0e9496ff92ffb39d63e796aa72c94fbbd550f5d5e619fed84e\nCopying blob sha256:23aaa4a63957b8f54c601bf8c5520e301e45f51b486ce62b36b600cc3b153798\nCopying blob sha256:d09470e21923f7e6cb698703a6a48ed3fe9a006f41232b71aedfb10bcd12dea9\nCopying blob sha256:48581178691b3b99b0ac8986bf06e9b31ab2f007e78d72e830aeb470c62787f7\nCopying blob sha256:2945eeaf3f39a4a66693f0d5031461a04540c4d4964ab27b325b8f2017757d52\nCopying blob sha256:f8052554dfbfaa4fc461f0c4dea5812ce0f7b90ccfca4659ce39b0bef0e35622\nCopying blob sha256:25cbea20d60b38a1e86d72ce765187236d18faefb1ca9eb79ffedb4004ba734a\nCopying blob sha256:709140fed4853987bbf082b8462dd1e239dc76caede1dd0e4a34932cd84068d3\nCopying blob sha256:4a0fdb28137ac64c3e614d137f53e0ac8ecfa837bfa857bae4e7d2c45111274b\nCopying blob sha256:cadca0a2adfbc431bb0ce8851b00e913173bdbcab8e636a132ba1aa4179f0274\nError: writing blob: uploading layer chunked: StatusCode: 413, \"<html>\\r\\n<head><title>413 Request Entity Too Large<...\"\n",
    "stderr_lines": [
        "Getting image source signatures",
        "Copying blob sha256:2360a13c13c9c9297eb2cbf7d01264286d7c187695a73b0d0dab760b20697aa5",
        "Copying blob sha256:ba882ef1cbf49f70c6594693b63b1a6cfdaa44f503b8c716722034dd5f137148",
        "Copying blob sha256:ad5362eb8973710afa7450bf83d239791333ed21195b84118618dedc15e41c96",
        "Copying blob sha256:9ec1ffde9a92f68f7318ff81660992dac7883eb90dc5d9929871a428bbf3f8d1",
        "Copying blob sha256:534da5c014b89c0e9496ff92ffb39d63e796aa72c94fbbd550f5d5e619fed84e",
        "Copying blob sha256:23aaa4a63957b8f54c601bf8c5520e301e45f51b486ce62b36b600cc3b153798",
        "Copying blob sha256:d09470e21923f7e6cb698703a6a48ed3fe9a006f41232b71aedfb10bcd12dea9",
        "Copying blob sha256:48581178691b3b99b0ac8986bf06e9b31ab2f007e78d72e830aeb470c62787f7",
        "Copying blob sha256:2945eeaf3f39a4a66693f0d5031461a04540c4d4964ab27b325b8f2017757d52",
        "Copying blob sha256:f8052554dfbfaa4fc461f0c4dea5812ce0f7b90ccfca4659ce39b0bef0e35622",
        "Copying blob sha256:25cbea20d60b38a1e86d72ce765187236d18faefb1ca9eb79ffedb4004ba734a",
        "Copying blob sha256:709140fed4853987bbf082b8462dd1e239dc76caede1dd0e4a34932cd84068d3",
        "Copying blob sha256:4a0fdb28137ac64c3e614d137f53e0ac8ecfa837bfa857bae4e7d2c45111274b",
        "Copying blob sha256:cadca0a2adfbc431bb0ce8851b00e913173bdbcab8e636a132ba1aa4179f0274",
        "Error: writing blob: uploading layer chunked: StatusCode: 413, \"<html>\\r\\n<head><title>413 Request Entity Too Large<...\""
    ],
    "stdout": "",
    "stdout_lines": []
}
```

however when I use the command
```
[lab-user@bastion testing]$ podman push controller.tn9zq.sandbox2741.opentlc.com/ee-minimal-rhel8:latest 
Getting image source signatures
Copying blob e01ce37cab43 skipped: already exists  
Copying blob 062be59d1294 skipped: already exists  
Copying blob e6e7e41943c3 skipped: already exists  
Copying config 5124f3a6e2 done   | 
Writing manifest to image destination
[lab-user@bastion testing]$ 
```

pushing to AAP 2.4 containerized RPM server.

Thanks.
