### ISSUE TITLE
[podman_container] Error: the --rm option conflicts with --restart, when the restartPolicy is not "" and "no"

### ISSUE THREAD

**Issue by paoloantinori** [containers/ansible-podman-collections#913]
When  `containers.podman.podman_container` is used and the flag `restart_policy: always` is used, the combination of configuration generates a Quadlet that constantly fails to start with this error:

```
Error: the --rm option conflicts with --restart, when the restartPolicy is not "" and "no"
``` 

Full sample task definition:

```yaml
    - name: Create Jellyfin Quadlet
      containers.podman.podman_container:
        name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        state: quadlet
        restart_policy: always
        quadlet_filename: jellyfin
        recreate: true
        ports:
          - "8096:8096"     # http
          # - "8920:8920"   # https
          - "7359:7359/udp" # udp Allows clients to discover Jellyfin on the local network.
          - "1900:1900/udp" # dlna Service discovery used by DNLA and clients.
        device:
          - "/dev/dri/renderD128:/dev/dri/renderD128"
        env:
          DOCKER_MODS: linuxserver/mods:jellyfin-opencl-intel # triggers automatic installation of drivers for Intel N100. Comes from lscr.io/linuxserver
          TZ: Europe/Rome
          PUID: "1000"
          PGID: "1000"
          UMASK: "022"
        user: "0:0"
        group_add:
          - "105" # adding to group render
        userns: keep-id
        volumes:
          - "{{ containers_config_path }}/jellyfin/library:/config:z"
          # - "{{ containers_config_path }}/jellyfin/transcode:/transcode:z"
          - "{{ storage_root_path }}:/data:z"
        pod: minix.pod
        network: host # this is required for DLNA and it's specific to Jellyfin
        quadlet_options:
          - "AutoUpdate=registry"
          - |
            [Install]
            WantedBy=default.target
```

```

cat $HOME/.config/containers/systemd/jellyfin.container 

[Container]
AddDevice=/dev/dri/renderD128:/dev/dri/renderD128
ContainerName=jellyfin
Environment=DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
Environment=TZ=Europe/Rome
Environment=PUID=1000
Environment=PGID=1000
Environment=UMASK=022
Group=0
Image=lscr.io/linuxserver/jellyfin:latest
Network=host
Pod=minix.pod
PublishPort=8096:8096
PublishPort=7359:7359/udp
PublishPort=1900:1900/udp
User=0
UserNS=keep-id
Volume=/home/pantinor/containers_config/jellyfin/library:/config:z
Volume=/run/media/5Tera/data:/data:z
PodmanArgs=--restart always
AutoUpdate=registry
[Install]
WantedBy=default.target
```
