### ISSUE TITLE
podman_container tmpfs & volume not idempotent due to formatting differences

### ISSUE THREAD

**Issue by sedrubal** [containers/ansible-podman-collections#918]
The arguments `tmpfs` and `volume` with an empty list seem not to be idempotent, but only due to differences in how they are formatted. This means, that containers are always recreated and restarted, even if there is no (real) difference. Below there is a minimal example to reproduce the behavior:

#### `playbook.yml`

```yml
---
- hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Run test container
      containers.podman.podman_container:
        name: ansible-test
        image: docker.io/library/debian:latest
        command: sleep 100
        state: started
        read_only: true
        tmpfs:
          "/srv/tmp/": "rw,size=512M"
        volume: []
```

#### Command to deploy the changes

```bash
$ ansible-playbook --diff playbook.yml
```

#### Diff that caused the re-deployment of the container:

```diff
-tmpfs - /var/lib/nginx/:rw,size=512m
-volume - None
+tmpfs - /var/lib/nginx/=rw,size=512m
+volume -
```
