### ISSUE TITLE
"--network slirp4netns:enable_ipv6=false" didnt't work

### ISSUE THREAD

**Issue by makar112233** [containers/ansible-podman-collections#919]
Hello.

I tried to run a container with different options.

```
  - name: 'kminion'
    image: 'redpandadata/kminion'
    version: 'version'
    installed: 'true'
    ports:
      - "5000:5000"
    volumes:
      - '/opt/kminion/kminion.yml:/opt/kminion.yml'
    render_volume_configs:
      - src: 'templates/kminion/'
        dst: '/opt/kminion/'
        conf_type: 'templated'
        sync: false
    env:
      CONFIG_FILEPATH: "/opt/kminion.yml"
    cmd_args:
      - "--runtime=runc"
      - "--cgroup-manager=cgroupfs"
    network:
      slirp4netns: "enable_ipv6=false"
```
But got an error:
[Step 5/11] fatal: [server]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.7"}, "changed": false, "msg": "argument 'network' is of type <class 'dict'> and we were unable to convert to list: <class 'dict'> cannot be converted to a list"}

Could you help, please, set correct option for network and add example to the documentation?
