### ISSUE TITLE
podman generate_systemd does not set want and require correctly

### ISSUE THREAD

**Issue by Xyz00777** [containers/ansible-podman-collections#927]
Hi, in this [discussion](https://github.com/containers/podman/discussions/25791) we found out that ansible is not setting minimum the require and want settings for a generated quadlet correct. they should be set like in this [commend](https://github.com/containers/podman/discussions/25791#discussioncomment-12803995) as [UNIT] configuration and not as Podman args because otherwise a race conditions happens where a container is not starting because the unit files for other dependent containers are not generated after system start at this time. As far as i understood.

**Comment by sshnaidm** [comment]
@Xyz00777 please provide all required info which was requested in issue. Playbook, task, logs, results.

**Comment by Xyz00777** [comment]
hi thanks for helping me :). sorry for not posting it directly. I took another look into the problem i was encountering and find out a little bit more:
i had the problem that when i was configuring the parameter [requires](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html#parameter-requires) its getting added as a container parameter which does not working together with a quadlet file because it will definitely at some time running into a race condition, where the other containers are not already created by the systemd service and the container is not waiting and failes because the other container services are not even created at the time of the start. I thought that parameter would be enough.
when i configure requires and wants as [generate systemd paramter](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html#parameter-generate_systemd) than it works. Even when i dont know why it works because i cant find where ansible is deploying the systemd unit file. And in the created .container unit file in the user folder for the container is no [UNIT] part created even when it should be created there as far as i understand the quadlet container workflow.



This is the script with the not working requires parameter:
```
- name: Deploy paperless using Podman Quadlet in user mode
  hosts: nextcloud
  become: true
  become_user: paperless
  vars:
    target_user: paperless
  tasks:
    - name: Define the Paperless-ngx Pod
      containers.podman.podman_pod:
        name: paperless
        state: quadlet
        quadlet_dir: ~/.config/containers/systemd/
        quadlet_file_mode: "0600"
        quadlet_filename: "{{ target_user }}.pod"
        generate_systemd:
          Requires: opt-paperlessngx.mount
          After: opt-paperlessngx.mount
        ports:
          - 8000:8000
        quadlet_options:
          - |
            [Install]
            WantedBy=default.target

    - name: Create Redis container
      containers.podman.podman_container:
        name: paperless-redis
        image: docker.io/library/redis:latest
        quadlet_dir: ~/.config/containers/systemd/
        quadlet_file_mode: "0600"
        quadlet_filename: "{{ target_user }}-redis.container"
        pod: paperless.pod
        generate_systemd:
          restart_policy: unless-stopped
        state: quadlet
        quadlet_options:
          - AutoUpdate=registry
          - |
            [Install]
            WantedBy=multi-user.target

    - name: Create PostgreSQL container
      containers.podman.podman_container:
        name: paperless-postgresql
        image: docker.io/library/postgres:latest
        quadlet_dir: ~/.config/containers/systemd/
        quadlet_file_mode: "0600"
        quadlet_filename: "{{ target_user }}-postgresql.container"
        pod: paperless.pod
        userns: keep-id
        user: 998:998
        generate_systemd:
          restart_policy: unless-stopped
        env:
          POSTGRES_USER: paperless
          POSTGRES_PASSWORD: paperless
          POSTGRES_DB: paperless
        volumes:
          - /opt/paperlessngx/pgdata:/var/lib/postgresql/data
        state: quadlet
        quadlet_options:
          - AutoUpdate=registry
          - |
            [Install]
            WantedBy=multi-user.target

    - name: Create Paperless-ngx webserver container
      containers.podman.podman_container:
        name: paperless-webserver
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        quadlet_dir: ~/.config/containers/systemd/
        quadlet_file_mode: "0600"
        quadlet_filename: "{{ target_user }}-webserver.container"
        pod: paperless.pod
        userns: keep-id
        user: 1000:1000
        generate_systemd:
        after:
            - paperless-postgresql.service
            - paperless-redis.service
          want:
            - paperless-postgresql.service
            - paperless-redis.service
            - paperless-tika
            - paperless-gotenberg
          restart_policy: unless-stopped
        env:
          PAPERLESS_REDIS: redis://paperless-redis:6379
          PAPERLESS_DBHOST: paperless-postgresql
          PAPERLESS_TIKA_ENABLED: 1
          PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
          PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
          PAPERLESS_OCR_LANGUAGE: deu+eng
          PAPERLESS_URL: https://paperless.example.org
          PAPERLESS_SECRET_KEY: xxxx-xxxxx
          PAPERLESS_CONSUMER_RECURSIVE: "true"
          PAPERLESS_OCR_DESKEW: true
          PAPERLESS_OCR_CLEAN: clean-final
          PAPERLESS_TIME_ZONE: Europe/Berlin
          #     PAPERLESS_EMAIL_TASK_CRON: "*/1 * * * *" # default is 10min
          USERMAP_UID: "1000"
          USERMAP_GID: "1000"
        requires:
          - "{{ target_user }}-tika"
          - "{{ target_user }}-gotenberg"
          - "{{ target_user }}-redis"
          - "{{ target_user }}-postgresql"
        volumes:
          - /opt/paperlessngx/data:/usr/src/paperless/data
          - /opt/paperlessngx/media:/usr/src/paperless/media
          - /opt/paperlessngx/export:/usr/src/paperless/export
          - /opt/paperlessngx/consume:/usr/src/paperless/consume
        state: quadlet
        quadlet_options:
          - AutoUpdate=registry
          - |
            [Install]
            WantedBy=multi-user.target

    - name: Create Tika container
      containers.podman.podman_container:
        name: paperless-tika
        image: docker.io/apache/tika:latest
        quadlet_dir: ~/.config/containers/systemd/
        quadlet_file_mode: "0600"
        quadlet_filename: "{{ target_user }}-tika.container"
        pod: paperless.pod
        generate_systemd:
          restart_policy: unless-stopped
        state: quadlet
        quadlet_options:
          - AutoUpdate=registry
          - |
            [Install]
            WantedBy=multi-user.target

    - name: Pull an image
      containers.podman.podman_image:
        name: docker.io/gotenberg/gotenberg:latest

    - name: Create Gotenberg container
      containers.podman.podman_container:
        name: paperless-gotenberg
        image: docker.io/gotenberg/gotenberg:latest
        image_strict: false
        quadlet_dir: ~/.config/containers/systemd/
        quadlet_file_mode: "0600"
        quadlet_filename: "{{ target_user }}-gotenberg.container"
        pod: paperless.pod
        generate_systemd:
          restart_policy: unless-stopped
        state: quadlet
        command: gotenberg --chromium-disable-javascript=true --chromium-allow-list=file:///tmp/.*

```
journald log:
```
systemctl --user status paperless-webserver.service
× paperless-webserver.service
     Loaded: loaded (/srv/paperless/.config/containers/systemd/paperless-webserver.container; generated)
     Active: failed (Result: exit-code) since Fri 2025-04-04 13:29:35 UTC; 1min 51s ago
    Process: 1635 ExecStart=/usr/bin/podman run --name=paperless-webserver --cidfile=/run/user/3001/paperless-webserver.cid --replace --rm --cgroups=split --sdnotify=conmon -d --user=1000:1000 --userns keep-id -v /opt/paperlessngx/data>
    Process: 1692 ExecStopPost=/usr/bin/podman rm -v -f -i --cidfile=/run/user/3001/paperless-webserver.cid (code=exited, status=0/SUCCESS)
   Main PID: 1635 (code=exited, status=125)
        CPU: 236ms

Apr 04 13:29:34 nextcloud1 systemd[1068]: Starting paperless-webserver.service...
Apr 04 13:29:34 nextcloud1 podman[1635]: 2025-04-04 13:29:34.817516022 +0000 UTC m=+0.110445768 image pull cf71d7b330d15de9eb08042419a400d20db29f2986d196daf3bd00d733372e76 ghcr.io/paperless-ngx/paperless-ngx:latest
Apr 04 13:29:34 nextcloud1 paperless-webserver[1635]: Error: "paperless-tika" is not a valid container, cannot be used as a dependency: no container with name or ID "paperless-tika" found: no such container
Apr 04 13:29:34 nextcloud1 systemd[1068]: paperless-webserver.service: Main process exited, code=exited, status=125/n/a
Apr 04 13:29:35 nextcloud1 systemd[1068]: paperless-webserver.service: Failed with result 'exit-code'.
Apr 04 13:29:35 nextcloud1 systemd[1068]: Failed to start paperless-webserver.service.
```
the created quadlet  file for the paperless web service which creates the require parameter as a container paramter:
```
[Container]
ContainerName=paperless-webserver
Environment=PAPERLESS_REDIS=redis://paperless-redis:6379
Environment=PAPERLESS_DBHOST=paperless-postgresql
Environment=PAPERLESS_TIKA_ENABLED=1
Environment=PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://paperless-gotenberg:3000
Environment=PAPERLESS_TIKA_ENDPOINT=http://paperless-tika:9998
Environment=PAPERLESS_OCR_LANGUAGE=deu+eng
Environment=PAPERLESS_URL=https://paperless.XXXX.XXX
Environment=PAPERLESS_SECRET_KEY=XXXXXX
Environment=PAPERLESS_CONSUMER_RECURSIVE=true
Environment=PAPERLESS_OCR_DESKEW=True
Environment=PAPERLESS_OCR_CLEAN=clean-final
Environment=PAPERLESS_TIME_ZONE=Europe/Berlin
Environment=USERMAP_UID=1000
Environment=USERMAP_GID=1000
Group=1000
Image=ghcr.io/paperless-ngx/paperless-ngx:latest
Pod=paperless.pod
User=1000
UserNS=keep-id
Volume=/opt/paperlessngx/data:/usr/src/paperless/data
Volume=/opt/paperlessngx/media:/usr/src/paperless/media
Volume=/opt/paperlessngx/export:/usr/src/paperless/export
Volume=/opt/paperlessngx/consume:/usr/src/paperless/consume
PodmanArgs=--requires paperless-tika,paperless-gotenberg,paperless-redis,paperless-postgresql
AutoUpdate=registry
[Install]
WantedBy=multi-user.target
```

when i use this script with the requires as a generate systemd paramter (shortened it now):
```
    - name: Create Paperless-ngx webserver container
      containers.podman.podman_container:
        name: paperless-webserver
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        quadlet_dir: ~/.config/containers/systemd/
        quadlet_file_mode: "0600"
        quadlet_filename: "{{ target_user }}-webserver.container"
        pod: paperless.pod
        userns: keep-id
        user: 1000:1000
        generate_systemd:
          after:
            - paperless-postgresql.service
            - paperless-redis.service
          want:
            - paperless-postgresql.service
            - paperless-redis.service
            - paperless-tika
            - paperless-gotenberg
          restart_policy: unless-stopped
        env:
          PAPERLESS_REDIS: redis://paperless-redis:6379
          PAPERLESS_DBHOST: paperless-postgresql
          PAPERLESS_TIKA_ENABLED: 1
          PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
          PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
          PAPERLESS_OCR_LANGUAGE: deu+eng
          PAPERLESS_URL: https://paperless.eisen5.eu
          PAPERLESS_SECRET_KEY: nWQxmR_R84ezEUu6xQZZ4n81Gae4JsDFhiDw_1sqtcQHqPFvDC4lSO-Uk63jcrq4jmU
          PAPERLESS_CONSUMER_RECURSIVE: "true"
          PAPERLESS_OCR_DESKEW: true
          PAPERLESS_OCR_CLEAN: clean-final
          PAPERLESS_TIME_ZONE: Europe/Berlin
          #     PAPERLESS_EMAIL_TASK_CRON: "*/1 * * * *" # default is 10min
          USERMAP_UID: "1000"
          USERMAP_GID: "1000"
#        requires:
#          - "{{ target_user }}-tika"
#          - "{{ target_user }}-gotenberg"
#          - "{{ target_user }}-redis"
#          - "{{ target_user }}-postgresql"
        volumes:
          - /opt/paperlessngx/data:/usr/src/paperless/data
          - /opt/paperlessngx/media:/usr/src/paperless/media
          - /opt/paperlessngx/export:/usr/src/paperless/export
          - /opt/paperlessngx/consume:/usr/src/paperless/consume
        state: quadlet
        quadlet_options:
          - AutoUpdate=registry
          - |
            [Install]
            WantedBy=multi-user.target
```
the generated unit file .config/containers/systemd/paperless-webserver.container looks like:
```
[Container]
ContainerName=paperless-webserver
Environment=PAPERLESS_REDIS=redis://paperless-redis:6379
Environment=PAPERLESS_DBHOST=paperless-postgresql
Environment=PAPERLESS_TIKA_ENABLED=1
Environment=PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://paperless-gotenberg:3000
Environment=PAPERLESS_TIKA_ENDPOINT=http://paperless-tika:9998
Environment=PAPERLESS_OCR_LANGUAGE=deu+eng
Environment=PAPERLESS_URL=https://paperless.eisen5.eu
Environment=PAPERLESS_SECRET_KEY=nWQxmR_R84ezEUu6xQZZ4n81Gae4JsDFhiDw_1sqtcQHqPFvDC4lSO-Uk63jcrq4jmU
Environment=PAPERLESS_CONSUMER_RECURSIVE=true
Environment=PAPERLESS_OCR_DESKEW=True
Environment=PAPERLESS_OCR_CLEAN=clean-final
Environment=PAPERLESS_TIME_ZONE=Europe/Berlin
Environment=USERMAP_UID=1000
Environment=USERMAP_GID=1000
Group=1000
Image=ghcr.io/paperless-ngx/paperless-ngx:latest
Pod=paperless.pod
User=1000
UserNS=keep-id
Volume=/opt/paperlessngx/data:/usr/src/paperless/data
Volume=/opt/paperlessngx/media:/usr/src/paperless/media
Volume=/opt/paperlessngx/export:/usr/src/paperless/export
Volume=/opt/paperlessngx/consume:/usr/src/paperless/consume
AutoUpdate=registry
[Install]
WantedBy=multi-user.target
```
even when it should look like:
```
[Unit]
After=paperless-redis.service paperless-postgresql.service
Requires=paperless-tika.service paperless-gotenberg.service paperless-redis.service paperless-postgresql.service
```

I hope that was understandable.
