### ISSUE TITLE
podman_container does not use authfile when doing the pull

### ISSUE THREAD

**Issue by rgordill** [containers/ansible-podman-collections#930]
With the following example:

```
- name: Run bootc-image-builder using Podman container
  containers.podman.podman_container:
    name: bootc-image-builder
    authfile: /etc/containers/auth.json
    rm: true
    detach: false
    interactive: true
    tty: true
    privileged: true
    pull: newer
    security_opt:
      - label=type:unconfined_t
    image: "registry.redhat.io/rhel9/bootc-image-builder:latest"
    volumes:
      - "/var/lib/containers/storage:/var/lib/containers/storage"
      - "/tmp/config.toml:/config.toml"
      - "/tmp/output:/output"
    command: "--type iso --config /tmp/config.toml bootc:latest"
    state: started
```

I am getting the following exception:

```
    "msg": "Can't pull image registry.redhat.io/rhel9/bootc-image-builder:latest",
    "stderr": "Trying to pull registry.redhat.io/rhel9/bootc-image-builder:latest...\nError: initializing source docker://registry.redhat.io/rhel9/bootc-image-builder:latest: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication\n",
```

The podman image pull is not using the authfile. Debuging in the remote host, I get the following:

```
May 08 14:20:55 builder python3[25882]: ansible-containers.podman.podman_container CUSTOM-DEBUG: Running command: podman image pull registry.redhat.io/rhel9/bootc-image-builder:latest
```

As it can be seen, the --authfile is not present, so it is raising the exception.
