### ISSUE TITLE
podman_tag is not idempotent

### ISSUE THREAD

**Issue by ericzolf** [containers/ansible-podman-collections#934]
Re-opening #900 and sorry for the delay, but an example doesn't help because _any_ example will show the issue.

Even though nothing changes (same image/checksum, same tags), the module always shows a change instead of sending back an OK.
As a user of the module, I want it to send back OK when all the target_names already exist for the same image ID as the image has.

Taking the example from the docs:

```yaml
- hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - containers.podman.podman_image:
        name: docker.io/continuumio/miniconda3
    - containers.podman.podman_tag:
        image: docker.io/continuumio/miniconda3
        target_names:
          - miniconda3
          - miniconda
```

Running the playbook twice, the first time both tasks are "changed", the second time, the first task is ok, but the second task (the tagging one) is still "changed" even though absolutely nothing changed.
