### ISSUE TITLE
podman_logout breaks when not logged in to specified registry

### ISSUE THREAD

**Issue by setpill** [containers/ansible-podman-collections#935]
Let's assume we have some playbook containing the following.

```yaml
- name: Login to private registry
  containers.podman.podman_login:
    username: user
    password: 'p4ssw0rd'
    registry: registry.example.internal

- name: Log out of private registry
  containers.podman.podman_logout:
    registry: registry.example.internal
```

This fails when running in check mode; the `podman_login` task is `skipped` but the `podman_logout` task is executed and fails with the error

```
Unable to gather info for registry.example.internal: Error: not logged into registry.example.internal
```

There might be 2 bugs here;

1. Inconsistency between `check mode` behaviour of `podman_login` and `podman_logout`.
2. Failure of idempotency in `podman_logout`
