### ISSUE TITLE
Containers being recreated with 'recreate: false'

### ISSUE THREAD

**Issue by stobbsm** [containers/ansible-podman-collections#936]
controller OS: fedora 41
client OS: Alpine 3.21

My containers are being recreated, the only difference in them seems to be
```diff
redirecting (type: become) ansible.builtin.doas to community.general.doas
--- before
+++ after
@@ -1 +1 @@
-systemd - false
+systemd - False
```
Relevant playbook section:
```yaml
- name: Create and start container
become: true
loop: "{{ containers }}"
loop_control:
  loop_var: container
containers.podman.podman_container:
  name: "{{ container.name }}"
  image: "{{ container.image }}:{{ container.tag | default('latest') }}"
  publish: "{{ container.ports | default(omit) }}"
  requires: "{{ container.requires | default(omit) }}"
  volume: "{{ container.volumes | default(omit) }}"
  network: "{{ container.network | default('default') }}"
  env: "{{ container.env | default(omit) }}"
  env_file: "{{ container.env_file | default(omit) }}"
  systemd: "{{ container.systemd | default(False) }}" # <- problem right here
  privileged: "{{ container.privileged | default(omit) }}"
  secrets: "{{ container.secrets | default(omit) }}"
  security_opt: "{{ container.security_opt | default(omit) }}"
  delete_depend: true
  pull: newer
  restart_policy: always
  recreate: false
```
I'm running this to control containers on a server, obviously, with a list of containers in a separate file.

Even when I set ```systemd: False``` it recreates it.
Removing the line altogether fixes it, as it now reports ```systemd - None```
Look like an error checking for 'False' instead of 'false'?
The client OS is Alpine 3.21, without systemd. Doesn't seem to change anything if I leave ```systemd``` unset, but disabling systemd shouldn't cause this kind of issue.

Edit: 

It seems that the ```systemd``` param defaults to 'true', as a string. Is that expected, or should it be a boolean?

[Lines 1421-1422 of podman_container_lib.py](https://github.com/containers/ansible-podman-collections/blob/ac5da409fedb139b20f40578cdf04957f5ef0166/plugins/module_utils/podman/podman_container_lib.py#L1421-L1422)
